CombatExtendedRWMod/CombatExtended

Defs/JobDefs/Jobs_Misc.xml, Defs/JobDefs/Jobs_Misc.xml.disabled, Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/CombatExtended/Comps/CompInventory.cs, Source/CombatExtended/CombatExtended/Defs/LoadoutGenericDef.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_UnloadYourInventory.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs, Source/CombatExtended/CombatExtended/Loadouts/HoldRecord.cs, Source/CombatExtended/CombatExtended/Loadouts/HoldTrackerAssignment.cs, Source/CombatExtended/CombatExtended/Loadouts/Loadout.cs, Source/CombatExtended/CombatExtended/Loadouts/LoadoutSlot.cs, Source/CombatExtended/CombatExtended/Loadouts/MapComp_LoadoutManager.cs, Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs, Source/CombatExtended/Harmony/Harmony-HediffComp_TendDuration_CompTended_Patch.cs, Source/CombatExtended/Harmony/HarmonyBase.cs
JobDriver_UnloadYourInventory:
-New JobDriver_UnloadYourInventory which asks HoldTracker concept about what should be dropped if anything.  This should prevent Pawn's inventory items which satisfy loadouts from being dropped.
-Disabled (but not removed) JobDriver_UnloadInvetory.  I don't know but I think this JobDriver was created for Issue #70 and if so was the wrong target.  NOTE: There may be some new methods that were added for this JobDriver.
Loadouts:
-Loadouts not saving/loading properly.
-Moved some of HoldTracker's methods into LoadoutManager class as that gets instantiated which is necessary for saving.
-Altered HoldTracker's structure to be a Dictionary<Pawn, List<HoldRecord>> instead of Dictionary<Pawn, Dictionary<ThingDef, HoldRecord>> to make it a bit easier to save. …
=> Added new JobDriver_UnloadYourInventory and worked on Loadouts.

Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs, Source/CombatExtended/Harmony/Harmony-Verb_TryStartCastOn_Patch.cs, Source/CombatExtended/Harmony/HarmonyBase.cs
Related to issue #29.
Took some time to find the interesting point where a pawn switches from trying to shoot to the warmup but finally found it.  From there did a Harmony Hybrid Infixed Prefix (functions like a Prefix but is Infixed).
The infix patch passes the instance verb into a needs reload check.  If the check returns false that means there was work to do (yeah, backwards) and the pawn shouldn't enter the warmup stance.  If true then either it wasn't a gun with ammo or it didn't need reload, the pawn enters the reload stance.
Thanks to whoever created/maintained the CompAmmoUser.TryStartReload() as I had no idea how to get turrets reloading and that just handled it for me.
Also includes some side fixes related to loadouts.
=> All CEVerb weapons that use ammo should do a reload before warmup.

Source/CombatExtended/CombatExtended/Jobs/JobGiver_CheckReload.cs
Or at least hopefully fixed #120 regarding the red error text.  Not sure about the other issues as I haven't been able to replicate.  Pawns with multiple weapons and ammo definitions seem to pick things up fine.
The issue seemed to be caused by a failure to check if the weapons in the inventory rangedWeaponCache had CompAmmoUser before trying to use said comp.
=> (Partial?) Fixed issue #120

Source/CombatExtended/CombatExtended/Jobs/JobGiver_CheckReload.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/Harmony/Harmony-AttackTargetFinder_BestAttackTarget_Patch.cs
Attempt to fix various issues related to drafted pawns auto-firing.
Issue 1: The code that inserted the call in IL was inserting it in the wrong place, breaking the key logic of the function.
Issue 2: The call to Verb_LaunchProjectileCE.GetPartialCoverBetween() had the 2nd and 3rd arguments backwards from the correct order, so was checking if the shooter had cover and if so the target was invalid (heh).
Issue 3: An older bug in GetPartialCoverBetween where the checkedCells list wasn't being updated with the cells which had been checked potentially reducing performance in all situations related to shooting.
=> Pawn auto firing issues

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Instead of putting the divider down under the button saved a copy of the key variable for use by the button before drawing the divider.
Should take care of issues in #126.
=> Re-fixed the button placement on inventory and added colonist check.

Source/CombatExtended/CombatExtended/Jobs/JobDriver_ReloadTurret.cs
There was some red error text on save load related to turrets, fixed.
Took a fair bit of back and forth with NIA but also fixed the issue with pawns dropping out of their job when reloading a turret (basically while going to the ammo to pick it up or when returning to the turret with the ammo in hand).
Also re-positioned the reload mote for after the pawn returns to the turret.
Some other logic changes due to the error checking that is being done earlier on.
=> Fixed a save/load issue (red text) on turrets, also job failure.

Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs, Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs
Changed how HoldTracker was used and didn't propagate that logic change out.
Issue had to do with HoldTracker could be empty and not just null.
Also cleaned up some logic that caused drop finding code to goof up pretty spectacularly if more than 1 HoldTracker record existed and the inventory wasn't 'just right'.
=> Fixed a bug in the logic of what to drop from loadouts/holdTracker

Languages/English/Keyed/Keys.xml, Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs, Source/CombatExtended/CombatExtended/Loadouts/MainTabWindow_OutfitsAndLoadouts.cs, Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs
Forced held items now show forced much like apparel (uses the same string).
Also the assign tab now has an extra button after edit loadout button which will show up if the pawn has any forced held items.  This button will clear the HoldTracker for that pawn.
=> Tweaked HoldTracker user interaction.  "forced" display and clear btn.

Defs/JobDefs/Jobs_CR.xml, Languages/English/Keyed/Keys.xml, Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_Reload.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_ReloadTurret.cs
Some of the remaining issues in #100.
Looking for feedback, in particular regarding turrets and the reportStrings in general.
-Removed "Reloaded!" mote (from CompAmmoUser).
-Added Keys (Translation strings) for motes, weapon source, and turret types.
-Modified Weapon and Turret Reload JobDrivers to use the new formatted motes.
-Added GetReport() override to generate a more detailed report of pawn activity.
Some light rearrangement and cleanup.
So reloading an equipped weapon shows the mote "Reloading Pistol!" and the reportString would say "Reloading equipped Pistol with <AmmoDef.LabelCap>".  Reloading an M240 turret shows the mote "Reloading turret M240" and the reportString "Reloading Manned Turret M240 with <AmmoDef.LabelCap>".
=> Modified motes and reportStrings for Reloading (includes turrets).

Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs, Source/CombatExtended/Detours/Detours_WorkGiver_InteractAnimal.cs, Source/CombatExtended/Harmony/Harmony-JobDriverWait-CheckForAutoAttack_Patch.cs, Source/CombatExtended/Harmony/Harmony-Verb_TryStartCastOn_Patch.cs, Source/CombatExtended/Harmony/Harmony-WorkGiver_InteractAnimal-TakeFoodForAnimalInteractJob.cs, Source/CombatExtended/Harmony/HarmonyBase.cs
Main Focus (issue #141):
-Added a HoldTracker notification to the detour of WorkGiver_InteractAnimal.TakeFoodForAnimalInteractJob.
-Modified the HoldTracker notification code to be a little more sane about how many things to hold onto.
-Removed (remark) some debug messages related to Notify_HoldTrackerJob.
Assides included in this:
-Cleaned out a bunch of debug log messages that got left behind in various Harmony patches.
-Moved some utility methods out of a specific patch and exposed them in HarmonyBase for use by any patcher.
-Added a new utility method to HarmonyBase.
-Attempted to perform the WorkGiver_InteractAnimal.TakeFoodForAnimalInteractJob modification as a Harmony patch before checking if there was a Detour (which there was).  Code is excluded from the project but the file is …
=> Attempted Fix Pickup-Drop Loop and cleaned up harmony patches some.

Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs
Surprised I didn't stumble on this sooner considering how often I've had pawns fetching generic pistol ammo but kasidoo (Discord) found this issue with Charged Rifles.
Issue was some old code from before generics assuming that all loadoutslots were thingdef based.  Fixed by referencing the found thing's def instead of the slot to decide if ingestible.
=> Fixed an NRE related to generic ammo fetching for loadouts.

Source/CombatExtended/Harmony/Harmony-FloatMenuMakerMap.cs
Basically I didn't catch when an action that another pawn could take over stabilizing and thus use the "ReservedBy" tidbit.
Could use attention when testing to see if the series of events is desired.
=> Found something in FloatMenuMakerMap that wasn't up to A17 standards.

Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/Harmony/Harmony-JobGiver_UnloadYourInventory.cs, Source/CombatExtended/Harmony/HarmonyBase.cs
The issue was that the jobgiver was unaware of loadouts and so would re-issue jobs that were closed successfully.
It was a bit weird in that they didn't always get stuck, suppose a race condition of sorts where sometimes the unloadinventory flag would get cleaned and others it wouldn't.
The patch proved a tad harder than expected since I had thought I needed an OR condition but I actually needed an AND.
Should take care of #70 finally.
=> Attempted fix to pawns getting stuck unloading their inventory.

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
AndrewZo (github) pinpointed the root cause, verified in debugger and verified fix.
Issue #188 should be fixed.
Melee does seem to yield XP, though possibly only from successful hits on mobile targets.  I wouldn't expect any XP from punching walls and trees.
=> Fixed no xp from shooting bug (thanks to AndrewZo)

Patches/RBSE/Bionics.xml
This is a patch for RBSE using the stats from EPOE's bionics.  RBSE uses the same parts as EPOE so their stats were copied from the EPOE patch.
=> Added patch file for Rah's Bionics and Surgery Expansion (RBSE)

Defs/Ammo/Rifle/56-56Spencer.xml
From Discord:
[3:04 PM] Xstamper: I also have a question, in Defs/Ammo/Rifle .56-56Spencer.xml, traderTags is CR_... so I can't make spencer ammo.
[3:05 PM] Xstamper: after changing CR to CE I can make it. Are this CR tags intentonal ones?
=> Fixed old CR_ tradetag --> CE_

Source/CombatExtended/CombatExtended/Jobs/JobDriver_Hunt.cs
Simply setting this.FailOn to not include "!victim.Dead" check at the
point of butchering the victim to prevent other things damaging the
victim causing the job to end.
=> Fix for #244

Source/CombatExtended/CombatExtended/Comps/CompFireModes.cs
CompFireModes.availableFireModes.ElementAt(0) caused errors if
availableFireModes.Count == 0 (by default) due to ChildrenAndPregnancy
doing some equipping/unequipping of pawns on world load
=> Fix for #278

Source/CombatExtended/CombatExtended/CE_Utility.cs
=> (This PR makes it so) Downed pawns don't crouch

Defs/Bodies/BodyShapes.xml
- human bodyshapedef now causes downed humans to have double width rather than the same width
=> Update BodyShapes.xml (small correction)

Source/CombatExtended/CombatExtended/CollisionVertical.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- CollisionVertical for doors is (0,0), 0 if open, otherwise the same as
for walls
- Door code removed from ProjectileCE
=> Better #358 fix

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Action = null if pawn is nonviolent (see changes)
=> Prevent the in-inventory equip functionality for nonviolent pawns

Source/CombatExtended/CombatExtended/Defs/LoadoutGenericDef.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs
- Use ThingRequestGroup whenever the lambda would just yield the things
form the ThingRequestGroup anyways (e.g _lambda = td => td.IsShell is
turned into thingRequestGroup = ThingRequestGroup.Shell)
=> Optimization for UpdateLoadout

Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs
- Map != null check
- assign compAmmo and use compAmmo instead of CompAmmo so all methods
aren't called twice
=> TurretGunCE ExposeData fix

Defs/Bodies/BodyPartGroups.xml, Patches/Core/Drugs/Drugs.xml, Patches/Core/HediffDefs/Hediffs_Local_AddedParts.xml, Patches/Core/ThingDefs_Items/Items.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/Core/ThingDefs_Misc/Weapons_Melee.xml, Patches/Core/ThingDefs_Misc/Weapons_RangedNeolithic.xml, Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Medival.xml, Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Modern.xml, Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Spacer.xml, Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
- GetUsedTool(tools, dinfo) to get the tool specified in dinfo. Contains
a lot of error logging whenever it can't find the exact tool used.
- IsWeapon -> IsMeleeWeapon check (this previously caused errors on
meleeing with ranged weapons)
- More error logging for augments and natural tools, to make sure the
XML gets updated at some point such that the method is able to
differentiate between tools
=> ArmorUtility.GetPenetrationValue revamp

Source/CombatExtended/CombatExtended/AmmoInjector.cs
- Check whether def.weaponTags != null. This was apparently the case for
MedievalTimes' ballista turret.
=> AmmoInjector error #425

Defs/ThingDefs_Misc/Ethereal_Various.xml, Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs, Source/CombatExtended/CombatExtended/DefOfs/CE_ThingDefOf.cs, Source/CombatExtended/CombatExtended/ExplosionCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Explosive.cs
Additionally fixes #423 BUG: Vanilla explosions will always occur on the cells below the roof, even if the explosive landed on top of the roof. This should be changed.
=> Roof explosions

Source/CombatExtended/CombatExtended/Defs/LoadoutGenericDef.cs
currently it lead to: 
Exception filling window for CombatExtended.Dialog_ManageLoadouts: System.InvalidOperationException: Operation is not valid due to the current state of the object
at System.Linq.Enumerable.Iterate[ThingDef,Single] (IEnumerable1 source, Single initValue, System.Func3 selector) [0x00000] in <filename unknown>:0 
at System.Linq.Enumerable.Max[ThingDef] (IEnumerable1 source, System.Func2 selector) [0x00000] in <filename unknown>:0 
at CombatExtended.LoadoutGenericDef.updateVars () [0x00000] in <filename unknown>:0 
at CombatExtended.LoadoutGenericDef.get_mass () [0x00000] in <filename unknown>:0 
at CombatExtended.Utility_Loadouts.GetWeightAndBulkTip (CombatExtended.LoadoutGenericDef def, Int32 count) [0x00000] in <filename unknown>:0 
at …
=> Fix loadout all ammo for gun setting

Defs/ManeuverDefs/Maneuvers.xml, Defs/MentalStateDefs/MentalStates.xml, Defs/PawnKindDefs/PawnKinds_CE.xml, Defs/ThingDefs_Buildings/Buildings_Defenses.xml, Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml, Patches/Core/ThingDefs_Misc/Filth_Various.xml, Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
- moved duplicate graphicData to match 1.0 definitions
- made ai_chillDestination false so pawns don't wander on barbed wire
=> More XML Error Fixes

Defs/ThingDefs_Buildings/Buildings_Turrets.xml, Defs/ThingDefs_Misc/Apparel_Shield.xml, Defs/ThingDefs_Plants/Plants_Cultivated_Farm.xml, Patches/Apparello/ThingDefs/ApparelHats_Famous.xml, Patches/Apparello/ThingDefs/ApparelHats_Various.xml, Patches/Apparello/ThingDefs/Apparel_Stuffed.xml, Patches/Core/ThingDefs_Buildings/Buildings_Security.xml, Patches/Core/ThingDefs_Misc/Apparel_Various.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml, Patches/Core/TraitDefs/Traits_Spectrum.xml, Patches/MechanoidsExtraordinaire/ThingDefs_Races/Races_Mechanoid_MechanoidsExtraordinaire.xml
ShootingAccuracy -> ShootingAccuracyPawn
nutrition -> Nutrition
Also this seems to be the Reason XML using CombatExtended.CompProperties_ExplosiveCE are broken:
Tried to use an uninitialized DefOf of type DamageDefOf. DefOfs are initialized right after all defs all loaded. Uninitialized DefOfs will return only nulls. (hint: don't use DefOfs as default field values in Defs, try to resolve them in ResolveReferences() instead) Debug info: DirectXmlToObject is currently instantiating an object of type CombatExtended.CompProperties_ExplosiveCE
=> ShootingAccuracy is now ShootingAccuracyPawn and ShootingAccuracyTurret

Patches/Core/Bodies/Bodies_Mechanoid/Scyther.xml, Patches/Core/HediffDefs/Hediffs_Local_AddedParts.xml, Patches/Core/PawnCapacityDefs/PawnCapacities.xml, Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml, Patches/Core/ResearchProjectDefs/ResearchProjects.xml, Patches/Core/ThingDefs_Buildings/Buildings_Security.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
- Bodies Scyther&Lancer the same
- ScytherBlade removed in 1.0
- BloodFiltr/BloodPump added in 1.0, Metabolism changed to "coolant
reservoir" flavour text
- Lancer (sniper) stops avoiding cover
- Lancer (sniper) and not Scyther (melee) have ammo
- Scyther/Lancer already have Blunt armor 0.2
- Lancer has fists/Hands instead of blades/Blades. Penetration value for
humanlike fists is used, and power value of 12 (vs human 9)
=> Mechanoid parts of #532

Patches/Core/FactionDefs/Factions_Misc.xml, Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml, Source/CombatExtended/CombatExtended/Comps/CompProperties_ExplosiveCE.cs, Source/CombatExtended/CombatExtended/DefOfs/CE_MentalStateDefOf.cs, Source/CombatExtended/CombatExtended/SuppressionUtility.cs
- Centipede -> Mech_Centipede
- defName=TribalChiefBase -> @Name=TribalChiefBase
- MentalStateDefOf.Wander_OwnRoom exists in 1.0, removed from CE and
replaced where used
- Now, explosionDamageDef is set in ResolveReferences, as in vanilla
=> More error log entries

Defs/ThingDefs_Misc/Apparel_Various.xml, Defs/ThingDefs_Misc/Weapons_Grenades.xml, Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml, Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Shadow rotation (ExactRotation) fixed
- Added water hitting effect to BulletCE (as in vanilla 1.0)
- Added Class="CombatExtended.ProjectilePropertiesCE" to all grenades so
they can use the grenade pin mote
- Fixed the FlakVest image path
=> Bullet, mote and graphics fixes

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Disable ability to craft Charge Lance by deleting recipeMaker, and removed SpacerGun weaponTag to prevent traders from selling it.
=> Charge Lance Availablity

Defs/RulePackDefs/RulePacks_DamageEvent.xml, Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs, Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs, Source/CombatExtended/CombatExtended/Things/AmmoThing.cs
- Spherical explosions are now scaled by Acos(2*[0,1] - 1) to allow for
the correct sphere random direction generation. Without this change,
cooking off bullets would mostly emerge towards the top of the sphere.
- A combat log system for cook off projectiles has been added to fix
#570
=> Sphere Explosions and Combat log fix for cookoff

Source/CombatExtended/Harmony/Harmony-DamageWorker_AddInjury.cs
Prevents the RNG from attempting to save inner core parts on destruction. Also stops inner core parts from being approximately 1.11x effective. Fixes #549
=> Patch damage worker to not randomly preserve inner parts on destruction

Source/CombatExtended/Harmony/Harmony-FloatMenuMakerMap.cs
Allow picking up more than one item from storage unit.
See: https://github.com/NoImageAvailable/CombatExtended/issues/693
=> Compatibility fix for LWM's DS, other storage mods

Defs/Stats/Stats_Pawns_Combat.xml, Defs/ThingDefs_Buildings/Buildings_Defenses.xml, Defs/ThingDefs_Buildings/Buildings_Turrets.xml, Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Gizmos/Command_Reload.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_Reload.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_TakeFromOther.cs, Source/CombatExtended/CombatExtended/Things/IncendiaryFuel.cs
- Fixed error log when non-violent colonists reload an auto-turret or a weapon they're carrying in inventory.
- Embrasures now have medium terrain affordance, to match solid walls.
- Heavy/charge auto-turret and 90mm construction no longer has a work amount of 1. Was caused by these being treated as a craftable instead of constructible.
- Incendiary fuel such as prometheum puddles can no longer spawn inside a closed door, as the puddle wouldn't be able to ignite until the door is opened.
- JobDriver_TakeFromOther was using pawn.CurJob to access targets, which caused errors if the job is temporarily kicked back into the queue (for example if the colonist starts vomiting). Using the job reference directly to avoid this.
- Added a functional workaround for #713, allowing the TakeFromOther …
=> Misc fixes

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
ProjectileCE.GetShotAngle can potentially be given velocity/range/gravity parameters that make it impossible to resolve a firing angle, due to exceedingly large distances combined with slow velocity. Part of the formula will attempt to get the square root of a negative number, which turns the return value into NaN, causing an error when spawning the projectile.
Mortars in particular are affected, when fired across large distances by an inaccurate shooter. The fix detects the unresolvable formula and manually sets the angle to provide maximum range.
=> Fix #734, Fix #735

Source/CombatExtended/CombatExtended/Jobs/WorkGiver_ReloadTurret.cs, Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs
Mannable turrets can be reloaded through hauling job or right-click context menu, as long as the turret isn't in use.
=> Allow manned turrets to be reloaded via haul job

Patches/Vanilla Apparel Expanded/Patch_Apparel_Industrial.xml, Patches/Vanilla Apparel Expanded/Patch_Apparel_Medieval.xml, Patches/Vanilla Apparel Expanded/Patch_Apparel_Neolithic.xml, Patches/Vanilla Apparel Expanded/Patch_Headgear_Industrial.xml, Patches/Vanilla Armour Expanded/Patch_Armor_Industrial.xml, Patches/Vanilla Armour Expanded/Patch_Armor_Medieval.xml, Patches/Vanilla Armour Expanded/Patch_Armor_Spacer.xml
Added patches for Vanilla Apparel Expanded (steamcommunity.com/sharedfiles/filedetails/?id=1814987817), fixed the broken xpaths in Patch_Armor_Spacer.xml which were causing the armor to remain unpatched, modified the stuff protection multipliers of some medieval armor.
=> Added compatibility patches for Vanilla Apparel Expanded, tweaked and fixed compatibility patches for Vanilla Armour Expanded.

Patches/Dragons!/ThingDefs_Races/Patch_Races_Animal_Dragons.xml, Patches/Spartan Foundry/ThingDefs_Misc/Patch_Apparel_Armors.xml, Patches/Spartan Foundry/ThingDefs_Misc/Patch_Apparel_Headgear.xml, Patches/Thrumkin/Patch_Implants_Prosthetics_Thrumkin.xml, Patches/Thrumkin/Patch_PawnKinds_Thrumkin.xml, Patches/Thrumkin/Patch_Race_Thrumkin.xml, Patches/Vanilla Apparel Expanded/Patch_Apparel_Industrial.xml, Patches/Vanilla Apparel Expanded/Patch_Apparel_Medieval.xml
Those 4 mods are: Thrumkin, RimWorld - Spartan Foundry, Vanilla Apparel Expanded and Dragon mod (Dragons!).
EDIT: The changes for the mods are:
- Thrumkin - removed unnecessary space and changed an xpath to be faster.
- RimWorld - Spartan Foundry - made the armor values of the armor more similar to CE power armor. Their protectionwas previously unpatched. At the same time debloated them by condensing xpaths of helmet and armor patches.
- Vanilla Apparel Expanded - changed some stuff protection multipliers for better or for worse.
- Dragon mod - debloated the entire patch.
=> Miscellaneous changes to 4 different mod compatibility patches.

Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs
Fix for ancient danger "Halfeaten" pawns spawning without arms, then
their loadout adding a shield and a warning telling us they can't wear
the shield because they don't have arms
=> Obscure colony start fix #2

Defs/Ammo/Flamethrower.xml, Defs/ThingDefs_Items/Items_Resource_Ammo.xml, Source/CombatExtended/CombatExtended/Things/AmmoThing.cs
- Flamethrower fuels Napalm and Prometheum now explode when damaged.
Both soak Prometheum. The napalm does slightly less damage and spreads
fuel puddles rather than prometheum ones.
- Prometheum explodes in 2.6 radius, spawning prometheum filth. The low
damage ensures that the whole stack can slowly cook off rather than
everything exploding at once. This should be balanced better.
- FSX explodes at once with 60 damage, Bomb in radius 3.5 (comparable to
frag grenades).
- To allow for this, TryLaunchCookOffProjectile now null-checks for
AmmoDef existing (which it doesn't on FSX and Prometheum).
- Cubic root of stackCount used for AmmoThing Detonate explosion scale
=> Make FSX, Prometheum and Flamethrower ammo explosive #753

Source/CombatExtended/CombatExtended/AmmoInjector.cs, Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/Defs/AmmoDef.cs, Source/CombatExtended/CombatExtended/Settings.cs, Source/CombatExtended/CombatExtended/Things/AmmoThing.cs
- Added UpdateLabel() function from Rimfire to update recipe names,
while deleting existing Job names' old recipe names (Reflection)
- Ensured Settings switches names behind guns in recipes when the toggle
is switched
- AmmoInjector now contains AddRemoveCaliberFromGunRecipes() which
checks whether names should be added or removed based on
CE_Utility.allWeaponDefs.
- AmmoInjector (e.g AFTER CE_Utility.allWeaponDefs is initiated) sets ammo descriptions to include AmmoCategoryDef stuff
- AmmoDef.AddDescriptionParts now contains what was usually in AmmoThing.DescriptionFlavor
=> Gun recipes now contain " (ammoSet.Label)" and the Ammo recipe description is expanded

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
Fix for ancient danger "Halfeaten" pawns' armor being destroyed
(happens like once in fifty game starts)
TakeDamage()->Apply->ApplyToPawn->ApplyDamageToPart->ArmorReroute->GetAfterArmorDamage
=> Obscure colony start fix #1

Defs/Ammo/Flamethrower.xml
Uses the standard ~Burn~ Flame def instead, as napalm is crafted with good ol' chemfuel.
=> Remove prometheum hediff from napalm

Defs/Ammo/AmmoCategoryDefs/AmmoCategories_Advanced.xml, Defs/Ammo/Flamethrower.xml
- Added dedicated categories to flamethrower ammo types
- Removed prometheum effect from napalm projectile
=> Flamethrower ammo tweaks

Defs/Ammo/Advanced/12x64mmCharged.xml, Defs/Ammo/Advanced/5x35mmCharged.xml, Defs/Ammo/Advanced/80x256mmFuelCell.xml, Defs/Ammo/Shell/81mmMortar.xml, Defs/Ammo/Shell/90mmCannon.xml, Source/CombatExtended/CombatExtended/AmmoInjector.cs
- Mechanoid ammo had tradeability = Sellable, which gave warnings. Someone removed the warnings by setting destroyOnDrop=false, but this meant the ammo still existed in the debug menu when the ammo system was off (and could still be found in say mission rewards).
- A new part was written in the AmmoInjector and new tradeTags were allowed so tradeability = Sellable is set when ammo is on, but it's set to None when ammo is off, fixing the issue.
- 90mm Cannon had an incorrect crafting base (GrenadeRecipeBase) which meant the crafting recipe still displayed in the machining table even with ammo turned off.
=> Fixed tradeable rounds, destroyOnDrop=false for some ammo

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
Removed unnecessary out-of-ammo mote during one-by-one reloads, as discussed recently in #659.
=> Remove unnecessary out-of-ammo mote

Source/CombatExtended/CombatExtended/Things/AmmoThing.cs
AmmoThing.GetInspectString() was trying to access AmmoDef and FSX/prometheum don't have it.
=> Fix error in FSX/prometheum inspect strings

Source/CombatExtended/CombatExtended/Jobs/JobDriver_TakeFromOther.cs
This is a correction of commit 2e3c08c that addresses #713, having now identified the root cause of the issue and implemented a better fix.
Turns out items maintain their forbid state while inside pack animals, and were causing the TakeFromOther job to fail repeatedly when a pawn wants to take a forbidden item from it. The options for fixing were to either not do forbid validation (same as UnloadInventory), or to add a check before the job is started. I opted for the former, as unloading already unforbids the items anyway as the pawns start hauling them, so might as well let colonists have a go at topping up their loadouts.
=> Fix JobDriver_TakeFromOther

Source/CombatExtended/CombatExtended/Loadouts/Dialog_ManageLoadouts.cs, Source/CombatExtended/CombatExtended/WeatherTracker.cs
- Fix for loadout window as reported in #773. Deleting the currently selected loadout now resets the window to the 'No loadout selected' state, instead of allowing unintended selection of the default 'Nothing' layout.
- Fixed the Beaufort scale property, it was using the internal _windStrength property rather than WindStrength, so it was ignoring the weather's wind modifier.
=> Loadout and wind fixes

Source/CombatExtended/CombatExtended/Things/Smoke.cs
Fixes an error that sometimes occurs with large fires, where some of the smoke particles have a null region.
```
Exception ticking Gas_BlackSmoke479726 (at (226, 0, 210)): System.NullReferenceException: Object reference not set to an instance of an object
at CombatExtended.Smoke.Tick () [0x00000] in <filename unknown>:0 
at Verse.TickList.Tick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```
=> Smoke null region check

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_Flammability.cs
- Fixed error in animal info window due to null apparel
- Apparel flammability was showing as int.MinValue for pawns with zero coverage, added check on division.
=> Flammability info fixes

Defs/Ammo/Advanced/6x24mmCharged.xml
Removed legacy armor penetration tags for cleanliness, and removed an extra zero that was in armorPenetrationKPA
=> Typographical correction.

Defs/Ammo/Rifle/127x55mmAR.xml
New types of rounds added. Old ammo updated to 1.6 standards.
1)AP-I, HE and Sabot in AmmoSet.
2)AP-I, HE and Sabot added in Ammo and reference the appropriate texture.
3)AP-I, HE and Sabot added in Projectiles and reference the appropriate damage values as per spreadsheet. Note their RHA is zero.
4)All entries in Projectiles updated to 1.6 standards. Legacy XML references removed.  RHA values not set.
5)API-I and Sabot added in Recipes. HE not added due to spreadsheet not displaying any ingredient cost.
=> Ammo updated to 1.6 standards.

Defs/Ammo/Grenade/30x29mmGrenade.xml, Defs/Ammo/Grenade/40x46mmGrenade.xml, Defs/Ammo/Rifle/303British.xml, Defs/Ammo/Rifle/545x39mmSoviet.xml, Defs/Ammo/Rifle/556x45mmNATO.xml, Defs/Ammo/Rifle/762x39mmSoviet.xml, Defs/Ammo/Rifle/762x51mmNATO.xml, Defs/Ammo/Rifle/762x54mmR.xml
A couple final tweaks/fixes for ammo. Updated the AP-HE labels to HE, changed 30 and 40mm grenade bulk to the current sheet value, added recipes for the 3 new ammo types for 5.45 Soviet which I overlooked, and corrected the ammo quantity in the recipe labels.
=> Final Ammo 1.6

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeDamage.cs
- #810 updated the statworker to allow min/max damage queries from pawns that have a null skills field, but I forgot to add an equivalent check to the stat's info window.
- Injuries not caused by a projectile or melee verb now skip armor modifiers, as these types of injuries (surgery failures, wounds added on spawn) aren't meant to roll against armor.
=> Melee and armor fixes

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
CompAmmoUser now recovers from invalid state when a weapon's caliber is changed, so previous instances of MAC-10 in the savefile won't have to be deleted.
=> CompAmmoUser caliber change detection

Source/CombatExtended/CombatExtended/LetterTracker.cs
The mechanoid warning letter is getting sent again every time the player quits to main menu and reloads the save. Putting the variable in the savefile so it only gets sent once per playthrough.
=> Store mechanoid letter state in savefile

Defs/Stats/Stats_Pawns_Combat.xml, Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
So that artificial arms don't get up to longsword-tier damage at high melee skill, the stat now works as an offset instead of multiplier, adding between 0 to 10 damage to the attack.
=> Unarmed damage stat as offset

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeStats.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
Ancient soldiers ignore the non-violent restriction, so they attempt to use the unarmed damage stat and cause console errors.
=> Fix unarmed damage stat being used by non-violent

Patches/GouRIMet/Items_GouRIMet.xml
Fixed parse issue that was causing the patch for GouRIMet to fail.
=> Fixed failed GouRIMet PatchOp

Patches/Dinosauria/Items_Resource_Dinosauria_Items.xml, Patches/Dinosauria/Items_Resource_Dinosauria_Stuff_Leather.xml
- Dino leathers changed for 1.6
- Triceraptor horn is not a weapon now like other animal trophies in CE.
=> Dinosauria leather stuff and trophy CE1.6

Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/Harmony/Harmony-GraphicApparelDetour.cs
If GraphicApparelDetour.dll is found in the currently loaded assemblies, detour it's injection method. Fixes pawn layer rendering issues caused by mods including this assembly.
=> Disable incompatible GraphicApparelDetour.dll detour injection.

Source/CombatExtended/Harmony/Harmony-Fire.cs
Multiplier of zero was preventing fire from spreading at all if there isn't any wind to push it around.
=> Fix fire never spreading while zero wind or indoors

Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/Harmony/Compatibility/Harmony-RunAndGun.cs
This seems like the easiest way to fix this. Being able to reload some weapons while moving would be cool and all, but that would only be realistic for some weapons. And more work than I'm interesting in putting in.
This approach, at least, fixes the conflict.
Closes #782
=> RunAndGun compatibility, prevent mobile reload attempts

Patches/CuprosAlloys/ThingDefs/Patch_Materials_Alloy_Utility.xml, Patches/Vanilla Armour Expanded/Patch_Armor_Spacer.xml, Patches/Vanilla Armour Expanded/Patch_Headgear_Industrial.xml
For Cupro's Alloys: made some alloys now be counted as "Steeled" materials (useable in armor vest production and alike);
For Vanilla Armor Expanded (or Vanilla Armour Expanded - i genuely don't care how it's supposed to be written because the name in the thumbnail of the mod and the name of the mod are different): tweaked armor values of spacer armor, modified coverage and layers of some headgear, made the balaclava thinner.
=> Modified patches for Cupro's Alloys and Vanilla Armor Expanded.

Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/Harmony/Compatibility/Harmony-BBBodySupport.cs, Source/CombatExtended/Harmony/Compatibility/Harmony-GraphicApparelDetour.cs
Adds apparel rendering compatibility for BBBodySupport, needed to support #921 
I took the soft touch with the logging, it's not an ancient DetoursLib job this time. And opinions on patching approaches aside, the prefix was written to detour for it's particular case only(which made it simple to patch).
Also moved this and the GraphicApparelDetour patch to a subdir and nested namespace, to avoid clutter.
Edit: Forgot to mention, this is currently dependent on author of BBBody removing a def file that overwrites the MiddleHead layer def(zozlin contacted the author). Seeing as that file is called "CE comp temp.xml", it's likely they'll oblige.
=> Apparel compatibility for BBBodySupport, move compatibility patches to subdir.

Source/CombatExtended/CombatExtended/Things/Smoke.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
For mortars (or any weapon that uses charges), the value of ShotSpeed is initialized on the first call to the property, and the calculated value is reused on every subsequent call. This causes problems when switching to targets at different ranges, as the weapon will keep using the speed calculated for its first shot, not the one it needs for the current shot. (e.g: fire a mortar at close range, the speed used will be 30, and now all rounds from that mortar will fly at 30 too, even when targeting locations that require higher speeds)
=> Fix mortar charges not adjusting speed when changing targets

Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/Harmony/Harmony_Pawn_DraftController.cs
Makes colonists properly stand down when told to hold fire while performing a manual attack, instead of just resetting their aim progress.
Note: this is a tweak to vanilla behavior and not directly related to CE, so I'm not sure if it belongs here, but given combat is the main focus I figured it might be a worthwhile addition.
=> Setting fire-at-will to off cancels current/pending attack orders

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
Without this change, the ammo gizmo displays the default ammo on spawned pawns.
=> Set selectedAmmo to correct value on spawned pawns

Defs/Stats/Stats_Basics_Inventory.xml, Languages/English/Keyed/BulkAndWeight.xml, Patches/Core/Stats/Stats.xml, Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Comps/CompInventory.cs, Source/CombatExtended/CombatExtended/Comps/CompProperties_AmmoUser.cs, Source/CombatExtended/CombatExtended/StatParts/StatPart_LoadedAmmo.cs
- CE_StatsReport_LoadedAmmo added to language keys (needs translation)
- Stats.xml patched to add CombatExtended.StatPart_LoadedAmmo to Mass stat
- Added file StatPart_LoadedAmmo
- CompAmmoUser now immediately calls UpdateInventory WHENEVER CurMagCount is changed, as it should be
- CompInventory stopped looking at loaded ammo for weight/bulk
- StatPart_LoadedAmmo was added, which does everything previously done in CompInventory, but which is common in current RimWorld versions
- Bulk StatDef now uses StatPart_LoadedAmmo
- AmmoUser CompProperties include a loadedAmmoBulkFactor with default value 0f. This allows RPG-7 and similar weapons to have a higher bulkiness (volume) when loaded.
- StatPart_LoadedAmmo multiplies by loadedAmmoBulkFactor when parentStat is Bulk
=> Fix #937 (loaded ammo has weight/bulk update properly)

Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs
- 17 months ago, during RW version change, the code in the method was changed to generateCommonality from a completely different tag which doesn't exist anymore
- generateAllowChance is commonly used to prevent things from being generated, while generateCommonality is not for preventing, just for weighting
- All CE XML uses generateAllowChance, not generateCommonality
- Therefore, this code change is necessary
=> Fix for #1038 (generateAllowChance instead of generateCommonality)

Source/CombatExtended/CombatExtended/Gizmos/Command_Reload.cs
- GroupsWith & MergeWith allow combining reloading gizmos when multiple things with guns are selected. All are stored in list "others"
- BuildAmmoOptions is refactored to allow taking into account multiple selected gun users:
- - Switching ammo for multiple users shows "(1/2) AP", for example, indicating that 1 gun is loaded with AP rounds and that there is another gun which could be loaded with these rounds.
- - Reloading multiple guns is possible
- - Unloading multiple guns is possible
Commit overall fixes #460
=> Fix for #460 (multi-selection of gun users allows ammo change for all)

Patches/Xenn/ThingDefs_Misc/Xenn_Ammo.xml, Patches/Xenn/ThingDefs_Misc/Xenn_Weps.xml, Patches/Xenn/ThingDefs_Races/Race_Xenn.xml
* Reimplement Xenn ammo as conditional patches
* Update Xenn weapon melee tools
* Update Xenn race melee tools
Note - further revision of the Xenn ammo will be done post-CE 2.0:
* The two weapons are meant to fire different ammo (one hot, one cold), rather than sharing one universal ammoset
* The previous patch author incorrectly described a freezing ammo cartridge as thermobaric
=> Update Xenn patches

Patches/Turret Collection/TurretCollection_CE_Patch_Turrets.xml
Notes:
* Turret weapon stats calculated using the [CE:FT Gun Stats spreadsheet](https://docs.google.com/spreadsheets/d/1Z9ZBnwRQWCKQm18O4I9ja4mFwLVChkNNfam2ZeQTTa0/edit#gid=1573763037)
* Includes an indirect-fire variant of the M74 Incendiary rocket projectile
* This allows the same generic M74 rocket ammo that exists in the CE library to be used for both direct-fire weapons (e.g. M202 FLASH) and indirect-fire turrets (e.g. this mod's Incendiary Launcher turret)
=> Add Turret Collection patches

Patches/DefensiveMachineGunTurretPack/ThingDefs/DMGT_Defensive_Turrets.xml, Patches/DefensiveMachineGunTurretPack/ThingDefs/DMGT_Sentry_Turrets.xml
* Turret weapon stats re-calculated using the [CE:FT Gun Stats spreadsheet](https://docs.google.com/spreadsheets/d/1Z9ZBnwRQWCKQm18O4I9ja4mFwLVChkNNfam2ZeQTTa0/edit#gid=1573763037)
* Reduced a number of turret ranges to more reasonable values
* Fixed incorrect turret range display radius
=> Update DMGT pack patches

Source/CombatExtended/CombatExtended/AmmoInjector.cs, Source/CombatExtended/CombatExtended/Things/AmmoThing.cs
Changes:
- AmmoInjector doesn't toggle menuHidden and destroyOnDrop when tradeTags contains CE_Ammo
- AmmoThing doesn't destroy every tick with ammo system disabled if tradeTags doesn't contain CE_Ammo
This fixes the issue where almost every AmmoDef is deleted when the ammo system is disabled
=> Actually implement CE_Ammo tag

Patches/Soviet Armory/SovietArmory_CE_Patch_Turrets.xml, Patches/Soviet Armory/SovietArmory_CE_Patch_Weapons.xml
Notes:
* Gun and Turret weapon stats calculated using the [CE:FT Gun Stats spreadsheet](https://docs.google.com/spreadsheets/d/1Z9ZBnwRQWCKQm18O4I9ja4mFwLVChkNNfam2ZeQTTa0/edit#gid=1573763037)
* Turrets have `<recoilPattern>Mounted</recoilPattern>` specified
* TP-82 Cosmonaut Survival Pistol currently only fires a single 5.45x39mm Soviet round before reloading, for CE purposes; in real-life, it also fires custom 12.7x70mm shotgun shells, which currently does not exist in the generic ammo library
* Perhaps we should ignore this until #1059 is implemented
=> Add Soviet Armory patches

Patches/PowerArmour T-45b/T45b_CE_Patch.xml
Patch brought over as part of the FastTrack merger
As the armor and helmet comes from a sci-fi video game, armor ratings are based on conjecture.
=> Add T-45b Power Armor patch

Patches/More Vanilla Turrets/MVT_CE_Patch_Ammo_Shells.xml, Patches/More Vanilla Turrets/MVT_CE_Patch_Buildings_Security.xml
Notes:
* Turret weapon stats calculated using the [CE:FT Gun Stats spreadsheet](https://docs.google.com/spreadsheets
* Due to the genericized names of the MVT turrets, stats were chosen based on the closest equivalent real-life weapon (e.g. Gun Complex = M2 Browning, Rocket Complex = Mounted version of the SMAW)
* Turrets have `<recoilPattern>Mounted</recoilPattern>` specified
* Conditionally-patched mod-unique 81mm Mortar (Plasma) shell and projectile
=> Add More Vanilla Turrets patches

Patches/Android Tiers/Ammo/MastiffShotgunShell.xml, Patches/Android Tiers/Ammo/X5Pistol.xml, Patches/Android Tiers/PawnkindDefs/PawnKinds_Android.xml, Patches/Android Tiers/ThingDef_Misc/Weapons_Guns.xml, Patches/Android Tiers/ThingDef_Races/AlienRace_Androids.xml
* Add the following mod-unique ammo:
* X-5 Pistol cartridge
* Mastiff Shotgun shell
* Change ammunition for the following Mech weapons:
* 40mm Cannon now uses 40x365mm Bofors shells
* X-5 Pistol now uses X-5 Pistol cartridges
* Mastiff Shotgun now uses Mastiff Shotgun shells
* Adjust M7 Mech loadout so that they spawn with a primary weapon (40mm Cannon or Mastiff Shotgun), a sidearm (X-5 Pistol), a mech combat knife and ammunition for both primary and sidearms
* Adjust M7 Mech CarryBulk and CarryWeight capacity to allow them to carry their (increased) inventory
NOTE: This is WIP - the X-5 Pistol cartridge and Mastiff Shotgun shell are currently not responding well to conditional patching
=> Update Android Tiers patches

Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Turrets.xml, Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Grenades.xml, Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Melee_JPN.xml, Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_FR.xml, Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_GER.xml, Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_JPN.xml, Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_UK.xml, Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_US.xml, Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_USSR.xml
Notes:
* Gun and Turret weapon stats calculated using the [CE:FT Gun Stats spreadsheet](https://docs.google.com/spreadsheets/d/1Z9ZBnwRQWCKQm18O4I9ja4mFwLVChkNNfam2ZeQTTa0/edit#gid=1573763037)
* Throwable Grenade stats calculated using the [CE:FT Ammo & Projectile Stats spreadsheet](https://docs.google.com/spreadsheets/d/1-y3KCuTM_vJnxw-gQPl5KIiz7ySd7fw9P6Wx4zB5bZg/edit#gid=1198674278)
* Melee tools standardized as per generic CE weapons 
* Turrets have `<recoilPattern>Mounted</recoilPattern>` specified
=> Add [Pratt] WWII Weapons Pack patches

Patches/Glitter Tech/GlitterTech_CE_Patch_Ammo_Shells.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Apparel_AdvancedShield.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Apparel_NanoSuitArmour.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Apparel_OrionCo.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Bodies_Mechanical.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_HeDiffs_AddedParts.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_HeDiffs_OCAddedParts.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_PawnKindDefs.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Races_Mechanical.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_TraderKinds.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Turrets.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Weapons_APB-1Group.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Weapons_EMRG-1.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Weapons_MRG-5Group.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Weapons_OCGroup.xml, Patches/Glitter Tech/GlitterTech_CE_Patch_Weapons_OCTurrets.xml
Notes:
* Patches conditionally support both the original Glitter Tech mod and its No Surgery version
* Gun and Turret weapon stats calculated using the [CE:FT Gun Stats spreadsheet](https://docs.google.com/spreadsheets/d/1Z9ZBnwRQWCKQm18O4I9ja4mFwLVChkNNfam2ZeQTTa0/edit#gid=1573763037)
* All weapons only use ammo that already exist in the main CE library
* Custom AmmoSets for the automatic mortars, which exclude antigrain warheads so players don't accidentally waste them on rapid-fire salvos
* Melee tools standardized as per generic CE weapons 
* Turrets have `<recoilPattern>Mounted</recoilPattern>` specified
=> Add Glitter Tech patches

Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_Apparel_Armor_Headgear.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_Apparel_OnSkin.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_BaseWeapons.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_Bodies_Mechanical.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_BodyParts_Mechanical.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_PawnKinds.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_Races_Mechanical.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_Races_Quadcopter.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_BigGuns.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_HRT_Pack.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_LMG.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_M_BoltAction.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_M_DMR.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_QuadcopterGuns.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_R_AK_Style.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_R_Bullpup_Style.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_R_Others.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_SMG.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_Shotguns.xml, Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_TankGuns.xml
=> Add Red Horse Faction - Cordis Die patches

Patches/CP British Military Kit/CP_BMK_CE_Patch_Apparel_Armor.xml, Patches/CP British Military Kit/CP_BMK_CE_Patch_Apparel_Armor_Headgear.xml, Patches/CP British Military Kit/CP_BMK_CE_Patch_Apparel_Backpacks.xml, Patches/CP British Military Kit/CP_BMK_CE_Patch_Apparel_Belts.xml, Patches/CP British Military Kit/CP_BMK_CE_Patch_Apparel_Headgear.xml, Patches/CP British Military Kit/CP_BMK_CE_Patch_Apparel_OnSkin.xml, Patches/CP British Military Kit/CP_BMK_CE_Patch_Apparel_Shell.xml
=> Add CP British Military Kit patches

Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_Apparel_Armor.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_Apparel_Armor_Headgear.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_Apparel_Backpacks.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_Apparel_Headgear.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_Apparel_OnSkin.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_PawnKindDefs.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_RangedIndustrial_LMG.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_RangedIndustrial_M_BoltAction.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_RangedIndustrial_R_AR_Style.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_RangedIndustrial_SF_Pack.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_RangedSpecial_AirSupport.xml, Patches/CP Spec Ops The Line/CP_SOTL_CE_Patch_Scenario.xml
=> Add CP Spec Ops The Line patches

Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Armor.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Armor_Headgear.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Armor_Headgear_Crafting_Rimfeller.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Backpacks.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Belts.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Headgear.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_OnSkin.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Shell.xml
=> Add Rimmu-Nation Clothing patches

Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Apparel_Armor_Headgear.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Apparel_OnSkin.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Apparel_Shell.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Bodies_Mechanical.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_BodyParts_Mechanical.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_MeleeNeolithic.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_PawnKinds_BarbieGirls.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_PawnKinds_LMM.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Races_Mechanical.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_BigGuns.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_HRT_Pack.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_LMG.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_M_BoltAction.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_M_DMR.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_Pistols.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_R_AK_Style.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_R_AR_Style.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_Revolvers.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_SMG.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_Shotguns.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_TankGuns.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Scenarios_LMM.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_TraderKinds.xml
=> Add Red Horse Faction - Last Man Contingent patches

Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_Apparel_Belts.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_Apparel_OnSkin.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_Apparel_Shell.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_MeleeWeapon.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_PawnKinds_EliteCrew.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_BigGuns.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_Grenades.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_LMG.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_M_BoltAction.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_M_DMR.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_Pistols.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_R_AK_Style.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_SMG.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_Shotguns.xml, Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_TraderKinds.xml
Notes:
* Throwable RGD-5 and C4 stats calculated using the [CE:FT Ammo & Projectile Stats spreadsheet](https://docs.google.com/spreadsheets/d/1-y3KCuTM_vJnxw-gQPl5KIiz7ySd7fw9P6Wx4zB5bZg/edit#gid=1198674278)
=> Add Red Horse Faction - Elite Crew patches

Defs/DamageDefs/Damages_LocalInjury.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_Ammo_NonLethal.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_Apparel_Armor.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_Apparel_Armor_Headgear.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_Apparel_Headgear.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_Apparel_OnSkin.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_MeleeWeapon.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_PawnKindDefs.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_RangedIndustrial_Pistols.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_RangedIndustrial_R_Bullpup_Style.xml, Patches/CP Metal Gear Solid/CP_MGS_CE_Patch_Scenario.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_Apparel_OnSkin.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_Apparel_Shell.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_NonLethal_Guns.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_PawnKinds_MSF_Soldiers.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_BigGuns.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_LMG.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_M_BoltAction.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_M_DMR.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_R_AK_Style.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_R_AR_Style.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_R_Bullpup_Style.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_R_Other.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_Scenarios_MSF.xml, Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_TraderKinds.xml
Notes:
* Added the following conditionally-patched mod-unique ammo:
* 9x19mm Parabellum Tranq pistol cartridge
* 7.62x51mm NATO Tranq rifle cartridge
* (Ammo is shared by both mods)
* High Frequency Blade from Metal Gear Solid uses original mod capacities, but has custom CE melee sharp and blunt armor penetration values specifically tuned according to the original mod author's request
* …
=> Add CP Metal Gear Solid and Red Horse Faction - MSF patches

Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_Apparel_Armor_Headgear.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_Apparel_OnSkin.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_PawnKinds_141.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_BigGuns.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_HRT_Pack.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_LMG.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_M_BoltAction.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_M_DMR.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_R_AK_Style.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_R_AR_Style.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_Shotguns.xml, Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_TraderKinds.xml
=> Add Red Horse Faction - Task Force 141 patches

Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_Apparel_Armor_Headgear.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_Apparel_Backpacks.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_Apparel_OnSkin.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_Apparel_Shell.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_PawnKinds_Ghosts.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_RaceKinds_Doggo.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_RangedIndustrial_BigGuns.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_RangedIndustrial_LMG.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_RangedIndustrial_M_DMR.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_RangedIndustrial_R_AK_Style.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_RangedIndustrial_R_AR_Style.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_RangedIndustrial_SMG.xml, Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_TraderKinds.xml
=> Add Red Horse Faction - The Ghosts patches

Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_Apparel_Armor_Headgear.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_Apparel_OnSkin.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_Apparel_PMCBali_Headgear.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_Apparel_Shell.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_BaseWeapons.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_Bodies_Mechanical.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_BodyParts_Mechanical.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_PawnKinds_UmbraCompany.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_Races_Mechanical.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_BigGuns.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_HRT_Pack.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_LMG.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_M_BoltAction.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_M_DMR.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_R_Others.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_SMG.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_Shotguns.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_TankGuns.xml, Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_TraderKinds.xml
=> Add Red Horse Faction - Umbra Company patches

Patches/CP Military Furniture/CP_MilitaryFurniture_CE_Patch_Apparel_Armor.xml, Patches/CP Military Furniture/CP_MilitaryFurniture_CE_Patch_Apparel_Armor_Headgear.xml, Patches/CP Military Furniture/CP_MilitaryFurniture_CE_Patch_Apparel_OnSkin.xml, Patches/CP Military Furniture/CP_MilitaryFurniture_CE_Patch_Apparel_PMCBali_Headgear.xml, Patches/CP Military Furniture/CP_MilitaryFurniture_CE_Patch_Apparel_Shell.xml, Patches/CP Military Furniture/CP_MilitaryFurniture_CE_Patch_PawnKinds_RecruitableContractor.xml, Patches/CP Military Furniture/CP_MilitaryFurniture_CE_Patch_RangedIndustrial_HRT_Pack.xml
Notes:
* Mod was previously called Red Horse Furniture
* Contrary to the mod's name, the included patches are actually for the recruitable ANVIL contractor pawns and their equipment
=> Add CP Military Furniture patches

Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Ammo_12Gauge_Dual.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Ammo_BfgCell.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Ammo_EmgMkVPistol.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Ammo_EmgPistol.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Ammo_GaussCannonFlechette.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Ammo_PlasmaCell.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Ammo_Rocket.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Apparel_Armor.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_Apparel_Armor_Headgear.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_BaseWeapons.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_LauncherDOOM_Weapons.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_MeleeDOOM_Weapons.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_CE_Patch_RangedDOOM_Weapons.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_KitClassic_CE_Patch_Ammo_ClassicEnergyCell.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_KitClassic_CE_Patch_Ammo_ClassicRocket.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_KitClassic_CE_Patch_Apparel_Armor.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_KitClassic_CE_Patch_Apparel_Armor_Headgear.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_KitClassic_CE_Patch_BaseWeapons.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_KitClassic_CE_Patch_LauncherDOOM_Weapons.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_KitClassic_CE_Patch_MeleeDOOM_Weapons.xml, Patches/CP DOOM & DOOM Kit Classic/CP_DOOM_KitClassic_CE_Patch_RangedDOOM_Weapons.xml
Notes:
* Gun stats based on extrapolation of real-life weapons, using the [CE:FT Gun Stats spreadsheet](https://docs.google.com/spreadsheets/d/1Z9ZBnwRQWCKQm18O4I9ja4mFwLVChkNNfam2ZeQTTa0/edit#gid=1573763037)
* Added the following conditionally-patched mod-unique ammo:
* 12 Gauge shotgun shell projectile variants (for simultaneous-firing double-barrel shotgun)
* UAC BFG Cell (Doom 2016)
* UAC EMG Pistol Mk V Cell (Doom 2016)
* UAC Plasma Cell (Doom 2016)
* UAC Rocket Mk VI (Doom 2016)
* UAC Energy Cell (Doom Classic)
* UAC Rocket Mk I (Doom Classic)
* All armor balanced to 1.6/1.8 standards, with respect to performance from original DOOM games
* Melee tools standardized as per generic CE weapons, …
=> Add CP DOOM and The DOOM Kit Classic patches

Patches/Core/FactionDefs/Factions_Misc.xml, Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
With the specific "smoke" and "EMP" grenadiers being of questionable effectiveness in a raid, this rebalances EMP grenadiers (smoke grenadiers are patched out) by converting them into an "advanced grenadier" pawnKind, with more weaponMoney and access to better weapons and sidearms.
Should generally be balanced with adjustment of their combatpower, but since I've allowed them to spawn w/ flashbangs, smoke grenades, and 40mm smoke rounds, there's the potential they might be weaker than intended--something to check in playtesting.
=> Convert EMP Grenadier into "Advanced Grenadier"

Royalty/Defs/ThingDefs_Buildings/Buildings_Mech_Spawners.xml
Simple hotfix of newly-added mech ammo beacon building label.
=> labels must be in lower case unless proper nouns

Defs/Ammo/Grenade/40x46mmGrenade.xml, Defs/Ammo/Shell/100x695mmR.xml, Defs/Ammo/Shell/120mmCannon.xml, Defs/Ammo/Shell/60mmMortar.xml, Defs/ThingDefs_Misc/Weapons_Ranged.xml, Patches/Core/ThingDefs_Races/Races_Animal_Tropical.xml
- Added market value to Explosive Bolt Projector, fixing issue of it not spawning.
- Changed 100mR and 120mm ammo reciple bases, resolving #975 
- Adjusted 40x46mm grenade stats based on CE Projectile sheet, following some research.
- Removed Explosive Bolt Projector graphic offset.
Links to the associated issues, e.g.
- Should close #975 
Check tests you have performed:
=> 1.1 - Ammo tweaks, mech Pikeman weapon fix.

Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Projectiles.xml, Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Races.xml
Notes:
* Race stats calculated using the [CE:FT Animal Stats spreadsheet](https://docs.google.com/spreadsheets/d/1aPTBeA6H3ANc8vH4FH7YbZ9i7lWj24gzh2nlvL3UTYY/edit#gid=1020770989)
* Animal tools and sharp/blunt armor penetration stats balanced relative to vanilla CE and other animal mod patches
=> Add Magical Menagerie patches

Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_PawnKinds_EliteCrew.xml
* Fix a number of incorrect PatchOps and defName references, which would otherwise indirectly cause RH: Elite Crew faction pawns to spawn without ammo for their weapons
- Closes #1155 
* Verified that all Elite Crew pawns now correctly spawn with primary & secondary weapons, ammo and knives in their inventory
=> Fix incorrect PatchOps causing RH Elite Crew pawns to have no ammo

Royalty/Patches/ThingDefs_Misc/Weapons_BladelinkMelee.xml, Royalty/Patches/ThingDefs_Misc/Weapons_Melee.xml
- Zeushammer: balanced to correspond with CE Melee power maul.
- Plasmasword: balanced to correspond with CE Melee wraith blade.
- Monoblade: reduced damage, increased cooldown.
- Initial stats for Ultra tech melee weapons too powerful, balance them to put them roughly on part with the high-rarity CE Melee weapons.
Check tests you have performed:
- [] Playtested a colony (specify how long)
=> Tweak Royalty Ultra tech weapon.

Patches/Sergal/Ammo_Sergal_LeadBall.xml, Patches/Sergal/Drugs.xml, Patches/Sergal/Gnoll_Weps.xml, Patches/Sergal/Lion_Weps_Ranged.xml, Patches/Sergal/PawnKinds_Frog.xml, Patches/Sergal/PawnKinds_Gnoll.xml, Patches/Sergal/PawnKinds_Lions.xml, Patches/Sergal/PawnKinds_Sergal.xml, Patches/Sergal/PawnKinds_SergalNME.xml, Patches/Sergal/PawnKinds_SergalTribe.xml, Patches/Sergal/PawnKinds_StripedGnollTribe.xml, Patches/Sergal/Race_Frog.xml, Patches/Sergal/Race_Lion.xml, Patches/Sergal/Race_Sergal.xml, Patches/Sergal/Race_StripedGnoll.xml, Patches/Sergal/Scenarios.xml, Patches/Sergal/Sergal_Apparel.xml, Patches/Sergal/Sergal_Weps.xml
* Add Lion and Frog race and pawnkinds
* Add Lion ranged weapons
* Pride Gauss Rifle (implementation equivalent to MRG-5 Rifle from Glitter Tech, chambered for 6mm Railgun sabots)
* Pride Machinegun (implementation equivalent to M249 LMG from RN Weapons, chambered for 6mm Railgun sabots)
* Pride Pistol (implementation equivalent to Desert Eagle from RN Weapons, chambered for infinite supply of "prothene acid bullets" from original Sergal mod)
* Add Lion apparel (balanced to equivalent vanilla CE apparel stats)
* Add drug bulk values (balanced to equivalent vanilla CE drug bulk values)
* Add conditionally-patched mod-unique Lead Ball ammo for Sergal Muskets
* Add appropriate ammo items to starting scenarios
* Update mod name to "Sergals Gnolls Lions and Frogs"
* Update Gnoll melee weapon …
=> Update Sergal et al patches

SupportedThirdPartyMods.md
* Rename Sergals, Gnolls and Lions to Sergals, Gnolls, Lions and Frogs
* Temporarily delist 11 mods whose patches have not yet been ported from FastTrack and missed the CE 2.0 release deadline
Note: these are documentation changes only, and have no effect on in-game behaviour
=> Update supported mod list (1 rename, 11 removals)

Patches/Vanilla Armour Expanded/Patch_Armor_Industrial.xml, Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml
- Vanilla Armor Expanded - Reduced bulletproof vest weight, increased bulk.
- Vanilla Weapons Expanded - Add one-handed tag to sawed-off shotgun
- While 10 is probably appropriate for a vest with a hard plate, the bulletproof vest is stated to be soft armor, so the weight has been reduced. Bulk also increased to something closer to other armor.
- Sawed off stats were generated with the intention of making it 1-handed, I just forgot the tag first time around.
=> Vanilla Expanded Adjustments
