Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs

Issue #69
Basically lifted some code from Rimworld so can also drop items from prisoner inventories now too.

Fixed unable to drop from pack animals.

---

Source/CombatExtended/CombatExtended/Jobs/JobDriver_Reload.cs

Issue #166.
Tested reloading manually, reloading equipped weapon automatically, and reloading inventory weapon.  All saves mid reload, loaded successfully.
Iterated over a few different possible solutions such as using a TargetC as a flag.  Settled on searching the Pawn's inventory/equipment via RimWorld object/properties for where the item was being reloaded from since asking for CE object properties isn't safe.
Additionally:
Swapped out references to TargetThing<Letter> with more helpful properties like holder and weapon.  Swapped out references to TargetIndex.<Letter> with more helpful properties like indReloader and indWeapon.  Both of these swaps done as it's what I've seen in other situations and generally requires less thought while maintaining the code.
Added some comments and …

Attempted to address reload job failure to load save.

---

Defs/ThingDefs_Misc/Weapons_Grenades.xml

Added resourceReadoutPriority First to grenades. This should fix #168. Also Means grenades will show up in the resource bar now. Would appreciate some feedback on this.

Fixed issue #168

---

Source/CombatExtended/CombatExtended.csproj
Source/CombatExtended/Detours/Detours_FloatMenuMakerMap.cs
Source/CombatExtended/Harmony/Harmony-FloatMenuMakerMap_Patches.cs
Source/CombatExtended/Harmony/HarmonyBase.cs

Should be complete and initial tests suggests that they work.
Comments are rather sparse/clumped and ugly/raw.

Detours_FloatMenuMakerMap into harmony patches.

---

Source/CombatExtended/CombatExtended.csproj
Source/CombatExtended/Harmony/Harmony-FloatMenuMakerMap_Patches.cs
Source/CombatExtended/Harmony/Harmony-VerbTracker_Patches.cs
Source/CombatExtended/Harmony/HarmonyBase.cs

In pure IL (for the heck of it and because it was a short patch, also for speed since the alternative would involve an extra call).
Also fixed up my remarks from the previous harmony work.
Related to #172.

Converted Detours_VerbTracker to Harmony patch.

---

Languages/English/Keyed/Keys.xml
Source/CombatExtended/CombatExtended/Jobs/JobDriver_Reload.cs

Now says "Reloading <weapon> with ammo".
Should fix #183

Fixed the NRE when reloading when ammo system is disabled.

---

Defs/Ammo/Grenade/25x40mmGrenade.xml
Defs/Ammo/Grenade/30x29mmGrenade.xml
Defs/Ammo/Grenade/40x46mmGrenade.xml
Defs/Ammo/Projectiles_Fragments.xml
Defs/Ammo/Rocket/RPG7.xml
Defs/Ammo/Shell/81mmMortar.xml
Defs/Ammo/Shell/90mmCannon.xml
Patches/Core/RecipeDefs/Recipes_Production.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Source/CombatExtended/CombatExtended/CE_Utility.cs
Source/CombatExtended/CombatExtended/Jobs/JobDriver_Reload.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectilePropertiesCE.cs
Source/CombatExtended/CombatExtended/Things/AmmoThing.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

-Added new gravity factor to fragments to reduce their max range
-Got rid of small/medium/large fragments distinction
-Fixed 81mm mortar shells not showing up ingame
-Added self-destruct to ammo things if ammo system is disabled

Fragmentation overhaul

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

Changed crafting costs to use formulas by BobDoleV. Generally work amount and crafting costs went down and with that market value. Will need to collect feedback on this change but would probably counteract increased crafting requirements from ammo.

Implemented crafting cost formulas

---

Patches/ADogSaid/Bionics.xml

Added armor penetration values and used CE defs for:
- SimpleProstheticLegAnimal
- SimpleProstheticArmAnimal
- JawAnimalSimple
- BionicLegAnimal
- BionicArmAnimal
- JawAnimalBionic

Patch for A Dog Said

---

Defs/Ammo/AmmoCategoryDefs/AmmoCategories_Neolithic.xml
Defs/Ammo/Medieval/CrossbowBolts.xml
Defs/Ammo/Neolithic/SlingBullet.xml
Patches/Vanilla-Friendly Weapons Expansion/ThingDefs_Misc/VFWE_Ranged_Medieval.xml
Patches/Vanilla-Friendly Weapons Expansion/ThingDefs_Misc/VFWE_Ranged_Modern.xml

Crossbow patched to work with CE, crossbow bolts added, improvised
pistol patched to be consistent with spreadsheet bar the fact it's now
stuffed, 'armour' to 'armor' for consistency.

Compatibilty with VFWE v2.2.2

---

Defs/Stats/Stats_Pawns_Combat.xml
Patches/Core/Drugs/Drugs.xml
Patches/Core/Stats/Stats.xml
Patches/Core/ThingDefs_Items/Items.xml

Beer and Wood Log now have armor penetration values, initial attempt at
shooting skill scaling for reload time, various minor accuracy fixes,
compatibility with Shooting Skill Rebalanced and similar mods, typo fix

31st Aug 2017

---

Defs/Ammo/Pistols/10mmAuto.xml
Defs/Ammo/Pistols/357SIG.xml
Defs/Ammo/Pistols/40SW.xml
Defs/Ammo/Pistols/454Casull.xml
Defs/Ammo/Rifle/3006Springfield.xml
Defs/Ammo/Rifle/4570Gov.xml

**Added more ammunition types.**
**Pistols**
-10mm Automatic (FMJ + AP + HP)
-.40 S&W (FMJ + AP + HP)
-.357 SIG (FMJ + ... yeah all of them have the same three types, you get the idea)
-.454 Casull
**Rifles**
-.30-06 Springfield (Because who doesn't love a good ping)
-.45-70 Government (because Rimworld is basically a western initially)

More Ammo Types

---

Defs/Ammo/Advanced/70mmMechanoidGrenade.xml
Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Chimera.xml
Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Goliath.xml
Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Hound.xml
Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Kraken.xml
Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Vespa.xml
Patches/MechanoidsExtraordinaire/BodyDefs/BodyParts_Mechanoid_Internal.xml
Patches/MechanoidsExtraordinaire/HediffDefs/Hediffs_Local_AddedParts_MechanoidsExtraordinaire.xml
Patches/MechanoidsExtraordinaire/PawnKindDefs/PawnKinds_MechanoidsExtraordinaire.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Misc/Weapons_Grenades_MechanoidsExtraordinaire.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Misc/Weapons_Guns_MechanoidsExtraordinaire.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Races/Races_Mechanoid_MechanoidsExtraordinaire.xml

Please tell me if I missed anything.

Added Mechanoids Extraordinaire patch

---

Languages/Russian/defInjected/RecipeDefs/Recipes_AmmoAdvanced.xml
Languages/Russian/defInjected/RecipeDefs/Recipes_AmmoHighCaliber.xml
Languages/Russian/defInjected/RecipeDefs/Recipes_AmmoPistols.xml
Languages/Russian/defInjected/RecipeDefs/Recipes_AmmoRifles.xml
Languages/Russian/defInjected/RecipeDefs/Recipes_AmmoShotgun.xml
Languages/Russian/defInjected/RecipeDefs/Recipes_Grenades.xml
Languages/Russian/defInjected/RecipeDefs/Recipes_Shells.xml
Languages/Russian/defInjected/ThingCategoryDefs/AmmoCategoryDef.xml
Languages/Russian/defInjected/ThingDefs/Ammo_Advanced.xml
Languages/Russian/defInjected/ThingDefs/Ammo_Grenades.xml
Languages/Russian/defInjected/ThingDefs/Ammo_HighCaliber.xml
Languages/Russian/defInjected/ThingDefs/Ammo_Neolithic.xml
Languages/Russian/defInjected/ThingDefs/Ammo_Pistols.xml
Languages/Russian/defInjected/ThingDefs/Ammo_Rifles.xml
Languages/Russian/defInjected/ThingDefs/Ammo_Shells.xml
Languages/Russian/defInjected/ThingDefs/Apparel.xml
Languages/Russian/defInjected/ThingDefs/Buildings.xml
Languages/Russian/defInjected/ThingDefs/Buildings_Turrets.xml
Languages/Russian/defInjected/ThingDefs/Items_Turrets.xml
Languages/Russian/defInjected/ThingDefs/Weapons_Grenades.xml
Languages/Russian/defInjected/ThingDefs/Weapons_Turrets.xml

This is attempt to finish translation to Russian. I translated not everything, but much.

Russian translation

---

Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs

CompAmmo.CurAmmoProjectile instead of this.GunCompEq.PrimaryVerb.verbProps.projectileDef

TurretGun use current ammo, not <projectileDef>

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

- Speed of projectiles
- flyOverhead instead of NeedsLineOfSight (which uses projectileDef)

More use of current ammo, not projectileDef

---

Defs/Tutor/Concepts_NotedOpportunistic.xml

Forgot to add CE_Crouching ConceptDef

---

Source/CombatExtended/CombatExtended/DefOfs/CE_ConceptDefOf.cs
Source/CombatExtended/CombatExtended/ShiftVecReport.cs

I swear this is the final missed stuff.

More CE_Crouch forgotten things

---

Source/CombatExtended/CombatExtended/CE_Utility.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs

Split off from the Projectile Arc PR

Fix for #40

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

IsPlant->IsTree in Verb_LaunchProjectileCE (code from Projectile Arc PR accidentally committed)

Small fix caused by ProjectileArc PR

---

Defs/Ammo/Neolithic/Javelins.xml
Defs/ThingDefs_Misc/Weapons_RangedNeolithic.xml

- thrown, javelins can be re-used 4 times
- fired, " " 2.5 times

Reusable javelins

---

Defs/Ammo/Grenade/40x46mmGrenade.xml

30x29 --> 40x46 mm for two projectiles

Minor label fix on a projectile

---

Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs

Earlier, with a large number of pawns on map with a small amount of ammo, caused serious freezes.

Revised formula for calculating ammo needs

---

Source/CombatExtended/CombatExtended/BoundsInjector.cs

Added some nullchecks to avoid bugs with compatibility for mods that changing plant graphics.

Added some nullchecks

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

Prevents error log spam when aiming tooltip appears on incapable of violence pawns

CapableOfViolence check in CanHitTargetFrom

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs

- more calculations
- much better looking (and actually accurate)
- works for all velocities, starting angles, works for fragments and for
cookoff, etcetera

Better projectile angle in arc

---

Defs/Bodies/BodyPartGroups.xml
Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Medival.xml
Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Modern.xml
Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Neolithic.xml
Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Spacer.xml

Changes to allow the patch to function in B18 (tools and some capitalization errors)

Rimfire patch update

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs

Attempt to fix #358

---

Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Medival.xml

Operation -> li

---

Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs

Incomplete but should fix #378

Split off TakeAndEquip.GetPriorityWork

---

Source/CombatExtended/CombatExtended/AmmoUtility.cs
Source/CombatExtended/Harmony/Harmony-LordToil_Siege.cs

As discussed in Discord - see changes

IsShell changes

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

Without it, centipedes cause errors

Null check for ShooterPawn.story

---

Defs/Ammo/Medieval/CrossbowBolts.xml
Defs/Ammo/Neolithic/GreatArrows.xml
Defs/Ammo/Neolithic/StreamlinedArrows.xml

- Crossbow bolts
- Great arrows
- Streamlined arrows

More visible arrow projectiles

---

Source/CombatExtended/CombatExtended/AmmoUtility.cs
Source/CombatExtended/CombatExtended/BoundsInjector.cs
Source/CombatExtended/CombatExtended/Comps_CCL/Def_Extensions.cs

As detailed in #365 
Furthermore, ThingDefOf is part of namespace RimWorld so a using RimWorld is added to AmmoUtility

BoundsInjectorFix & added missing "using" in AmmoUtility

---

Patches/EPOE/Bionics.xml

Verbs -> Tools
MeleeDamage -> Power
MeleePenetration -> ArmorPenetration

EPOE patch B18 (2.1)

---

Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Source/CombatExtended/Harmony/Harmony-VerbUtility.cs

- Changed ProjectileDef -> Projectile (name of method) in some files, to
be in accordance with B18's Verb_LaunchProjectile names
- Replaced defaultProjectile mentions with something like Projectile to
take into account ammoUsers and such
- Took into account CompChangeableProjectile in all Projectile-type get
methods

Removal of defaultProjectile and use of Projectile

---

Defs/Ammo/AmmoCategoryDefs/AmmoCategories_Neolithic.xml
Defs/Ammo/Neolithic/SlingBullet.xml
Patches/VFAS/HediffDefs/BionicArm.xml
Patches/VFAS/HediffDefs/BionicLeg.xml
Patches/VFAS/HediffDefs/SimpleProstheticArm.xml
Patches/VFAS/HediffDefs/SimpleProstheticLeg.xml
Patches/VFWE/Ammo/Pistols/38Special.xml
Patches/VFWE/DamageDefs/Damages_LocalInjury.xml
Patches/VFWE/PawnKindDefs_Humanlike/PawnKinds.xml
Patches/VFWE/ThingDefs_Misc/Weapons_Guns.xml
Patches/VFWE/ThingDefs_Misc/Weapons_Melee.xml
Patches/VFWE/ThingDefs_Misc/Weapons_RangedNeolithic.xml

Note: For the VFWE patch, an error is thrown relating to a patch in the Weapons_Guns.xml patch folder. However, I couldn't find the specified problem with Ctrl + F and the issue doesn't seem to have any effect on anything anyway.

Updated Patches

---

Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Modern.xml

Patch to remove the referances to the old techs from CE

RimfirePatchRemoveTech

---

Defs/Ammo/Advanced/30x64mmFuelCell.xml
Defs/Ammo/Advanced/70mmMechanoidGrenade.xml
Defs/Ammo/Advanced/80x256mmFuelCell.xml
Defs/Ammo/AmmoBases.xml
Defs/Ammo/AmmoCategoryDefs/AmmoCategories_Advanced.xml
Defs/Ammo/Grenade/25x40mmGrenade.xml
Defs/Ammo/Grenade/30x29mmGrenade.xml
Defs/Ammo/Grenade/40x46mmGrenade.xml
Defs/Ammo/Rocket/84x246mmR.xml
Defs/Ammo/Rocket/M72LAW.xml
Defs/Ammo/Rocket/RPG7.xml
Defs/Ammo/Rocket/RPO.xml
Defs/Ammo/Rocket/SPG9.xml
Defs/Ammo/Shell/81mmMortar.xml
Defs/Ammo/Shell/90mmCannon.xml
Defs/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml

- Explosives now use new vanilla damage falloff mechanic
- Added firefoam and antigrain mortar shells

Explosives update

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

Machine Pistol now uses TEC-9 stats and Heavy SMG uses stats derived from UMP45 information. Updated heavy SMG's melee tools to use stock/barrel instead of grip/barrel

updated SMGs

---

Patches/Core/Stats/Stats.xml
Source/CombatExtended/CombatExtended.csproj
Source/CombatExtended/CombatExtended/AmmoUtility.cs
Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
Source/CombatExtended/CombatExtended/BoundsInjector.cs
Source/CombatExtended/CombatExtended/CE_Utility.cs
Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs
Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs
Source/CombatExtended/CombatExtended/Comps/HediffComp_InfecterCE.cs
Source/CombatExtended/CombatExtended/Comps/HediffComp_Stabilize.cs
Source/CombatExtended/CombatExtended/Comps_CCL/Def_Extensions.cs
Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs
Source/CombatExtended/CombatExtended/Gizmos/Command_VerbTarget.cs
Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs
Source/CombatExtended/CombatExtended/Loadouts/Dialog_ManageLoadouts.cs
Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Explosive.cs
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_Caliber.cs
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeArmorPenetration.cs
Source/CombatExtended/CombatExtended/Things/Apparel_VisibleAccessory.cs
Source/CombatExtended/CombatExtended/Things/IncendiaryFuel.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCEOneUse.cs
Source/CombatExtended/Harmony/Harmony-SmokepopBelt.cs
Source/CombatExtended/Harmony/Harmony-Verb_TryStartCastOn.cs

Just picking most of the low-hanging fruits

compiler errors: 160 -> 74

---

Patches/Core/ResearchProjectDefs/ResearchProjects.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml

- no research
- removed from buildings_security

Remove Sniper & Heavy turret

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml
Defs/ThingDefs_Misc/Apparel_Shield.xml
Defs/ThingDefs_Plants/Plants_Cultivated_Farm.xml
Patches/Apparello/ThingDefs/ApparelHats_Famous.xml
Patches/Apparello/ThingDefs/ApparelHats_Various.xml
Patches/Apparello/ThingDefs/Apparel_Stuffed.xml
Patches/Core/FactionDefs/Factions_Misc.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml
Patches/Core/ThingDefs_Misc/Apparel_Various.xml
Patches/Core/ThingDefs_Misc/Filth_Various.xml
Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
Patches/Core/TraitDefs/Traits_Spectrum.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Races/Races_Mechanoid_MechanoidsExtraordinaire.xml

Check commit for more info.
Also, check balancing.
Info: Based on my other branch, therefore the additional commits.
Also, FilthFuel -> Filth_Fuel.

Factions_Misc Patch fixed.

---

Patches/Core/FactionDefs/Factions_Misc.xml
Patches/Core/Stats/Stats.xml
Source/CombatExtended/CombatExtended/TexButton.cs

- Centipe -> Mech_Centipede
- minValue is already 0 for ShootingAccuracyPawn (1.0)
- ShowEnvironment -> ShowBeauty

Development alicecomma5

---

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Source/CombatExtended/Harmony/Harmony-FloatMenuMakerMap.cs
Source/CombatExtended/Harmony/Harmony-TooltipUtility.cs

Translate(new object[] {a,b,c}) -> Translate(a,b,c)

---

Defs/Ammo/Shotgun/12Gauge.xml

Excessive additions/deletions are just from copying-pasting from Notepad++.

Commented out bird-shot

---

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml

Tested; Stranger in Black now spawns with ammo

Patched Stranger in Black

---

Source/CombatExtended/Harmony/Harmony-DamageWorker_AddInjury.cs

Harmony prefix result needs to be passed by ref

---

Defs/Ammo/HighCaliber/338LapuaMagnum.xml

Removed FSX requirement as well as changing the ammoClass to HollowPoint

Fixed .338 HP

---

Defs/Ammo/Advanced/30x64mmFuelCell.xml

Fix 30x64mm thermobaric explosion

---

Defs/Stats/Stats_Pawns_Inventory.xml
Languages/English/Keyed/BulkAndWeight.xml
Languages/Russian/Keyed/BulkAndWeight.xml
Source/CombatExtended/CombatExtended/Loadouts/Dialog_ManageLoadouts.cs
Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs
Source/CombatExtended/CombatExtended/Loadouts/Utility_Loadouts.cs

loadouts menu
-added pause when menu is opened.
-fixed low fps.
-some minor visual changes.
-plain(in-code) strings replaced by translatable strings.
gear tab
-added text overlay on weight and bulk bars.
-added detailed tooltip when hovering cursor over armor values оf creature.
-added item weight values.

few changes in gear tab and loadouts menu

---

Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs

DangerInPosRadius led to loss tps, removed.
Added ammofinder for weapon in inventory, if pawn has no primary weapon. After pick up ammo, pawn switch to the weapon.
Removed expiryIntervals, pawn didnt have time in ticks to reach the target and drop job.

Solving performance problems and new features.

---

Patches/Better Infestations/Patch_Race_Insect.xml
Patches/CuprosAlloys/ThingDefs/Patch_Materials_Alloy_Advanced.xml
Patches/CuprosAlloys/ThingDefs/Patch_Materials_Alloy_Decorative.xml
Patches/CuprosAlloys/ThingDefs/Patch_Materials_Alloy_Utility.xml
Patches/CuprosAlloys/ThingDefs/Patch_Materials_BaseMetal.xml
Patches/Dragons!/ThingDefs_Races/Patch_Races_Animal_Dragons.xml
Patches/Orassans/ThingDefs_Races/Orassan_Race.xml
Patches/Orassans/ThingDefs_Weapons/MeleeWeapon_kittyclaws.xml
Patches/Orassans/ThingDefs_Weapons/Weapons.xml
Patches/ROMB/ThingDefs_Items/Patch_Things_Bones.xml
Patches/Spartan Foundry/ThingDefs_Misc/Patch_Apparel_Armors.xml
Patches/Spartan Foundry/ThingDefs_Misc/Patch_Apparel_Headgear.xml
Patches/Thrumkin/Patch_Implants_Prosthetics_Thrumkin.xml
Patches/Thrumkin/Patch_PawnKinds_Thrumkin.xml
Patches/Thrumkin/Patch_Race_Thrumkin.xml
Patches/Thrumkin/Patch_Things_Thrumkin.xml

Added patches for these mods:
- Better Infestations (steamcommunity.com/sharedfiles/filedetails/?id=1319614331),
- Cupro's Alloys (steamcommunity.com/sharedfiles/filedetails/?id=1543189281),
- Dragon mod (steamcommunity.com/sharedfiles/filedetails/?id=1580356492),
- Orassans (steamcommunity.com/sharedfiles/filedetails/?id=1541519487),
- Rim of Madness - Bones (steamcommunity.com/sharedfiles/filedetails/?id=1180573408),
- Rimworld: Spartan Foundry (steamcommunity.com/sharedfiles/filedetails/?id=1695609511),
- Thrumkin (github.com/Syrchalis/Thrumkin).

Added patches for several mods.

---

Patches/Vanilla Armour Expanded/Patch_Armor_Industrial.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Medieval.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Neolithic.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Spacer.xml
Patches/Vanilla Armour Expanded/Patch_Headgear_Industrial.xml

Vanilla Armour Expanded mod's Steam Workshop page: steamcommunity.com/sharedfiles/filedetails/?id=1814988282

Added compatibility patches for the Vanilla Armour Expanded mod.

---

Source/CombatExtended/Harmony/ShieldBelt.cs

Previously the code didn't follow logic correctly, now it actually does what it's supposed to do.

Fixes the ShieldBelt prefix to be correct

---

Source/CombatExtended/CombatExtended.csproj
Source/CombatExtended/Harmony/Harmony-Thing.cs
Source/CombatExtended/Harmony/HarmonyThingDef.cs

Partial fix for #112 - the smelting weapons part

PostFix SmeltProducts to add any loaded ammo #112

---

Patches/GouRIMet/Items_GouRIMet.xml

Fixed oversight in initial patch.

Tweak to GouRIMet Patch

---

Patches/RimEffect Asari/Asari_Race.xml
Patches/RimEffect Asari/PawnKinds_Asari.xml

Integrate existing standalone patch for Xen's RimEffect - Asari of the Rim.

Add patch for Rimeffect Asari

---

Patches/Vanilla Armour Expanded/Patch_Armor_Medieval.xml

Attempted to tweak several values of the patches for metallic medieval armor from Vanilla Armour Expanded (steamcommunity.com/sharedfiles/filedetails/?id=1814988282).

Tweaked the viability of Vanilla Armour Expanded's medieval armor.

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

Stance is null while caravaning.

Fix error in caravan pawn info window

---

Patches/Gas Traps and Shells/ThingDef_Misc/AmmoCategories_Gas.xml
Patches/Gas Traps and Shells/ThingDef_Misc/Ammo_Gas.xml

AmmoCategories and shell Recipes added dynamically to support Gas Shells and Traps mod.

Add Gas Shells & Trap Patch

---

Patches/Core/Drugs/Drugs.xml
Patches/Core/ThingDefs_Items/Items_Resource_Stuff.xml
Patches/Core/ThingDefs_Misc/Weapons_Melee.xml

Updated melee weapons, wood log (as a weapon), and beer (as a weapon) to new melee stats and AP model.

Update Melee Weapon Stats and Convert to new AP model.

---

Defs/Ammo/Advanced/8x35mmCharged.xml

Updated with the latest calculations from Combat Extended physics spreadsheet.

Update to match spreadsheet calculations

---

Defs/Ammo/Neolithic/Arrows.xml
Defs/Stats/Stats_Weapons_Melee.xml
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeDamage.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs

Default tooltip:
When equipped by a pawn:

Skill-based melee damage variation

---

Source/CombatExtended/CombatExtended/Things/Smoke.cs

Closed vents no longer let smoke pass through them. Open vents still work as before.

Smoke vent tweak

---

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeDamage.cs

Fixes the melee statworker to account for pawns that can use equipment in melee, but don't have skill stats. (e.g: centipedes smacking people around with their heavy charge blaster)

Fix melee statworker

---

Defs/Ammo/Advanced/12x64mmCharged.xml
Defs/Ammo/Advanced/5x35mmCharged.xml
Defs/Ammo/Advanced/6x18mmCharged.xml
Defs/Ammo/Pistols/45ACP.xml
Defs/Ammo/Rocket/M72LAW.xml
Languages/English/Strings/NameBanks/SwearLibrary.txt
Languages/English/Strings/NameBanks/SwearLibrarySuppressed.txt
Patches/Core/HediffDefs/Hediffs_Local_AddedParts.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/Core/ThingDefs_Races/Races_Animal_Arid.xml
Patches/Core/ThingDefs_Races/Races_Animal_Bears.xml
Patches/Core/ThingDefs_Races/Races_Animal_BigCat.xml
Patches/Core/ThingDefs_Races/Races_Animal_Birds.xml
Patches/Core/ThingDefs_Races/Races_Animal_Farm.xml
Patches/Core/ThingDefs_Races/Races_Animal_Giant.xml
Patches/Core/ThingDefs_Races/Races_Animal_Hares.xml
Patches/Core/ThingDefs_Races/Races_Animal_Insect.xml
Patches/Core/ThingDefs_Races/Races_Animal_Pet.xml
Patches/Core/ThingDefs_Races/Races_Animal_Rodentlike.xml
Patches/Core/ThingDefs_Races/Races_Animal_Temperate.xml
Patches/Core/ThingDefs_Races/Races_Animal_Tropical.xml
Patches/Core/ThingDefs_Races/Races_Animal_WildCanines.xml
Patches/Core/ThingDefs_Races/Races_Humanlike.xml
Patches/Core/ThingDefs_Races/Races_Mechanoid.xml

Rebased and fixed variant of #816.

Animal stats

---

Defs/Stats/Stats_Weapons_Melee.xml
Patches/Core/Stats/Stats.xml
Source/CombatExtended/CombatExtended.csproj
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeArmorPenetration.cs
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeDamageAverage.cs
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeDamageBase.cs

- Melee AP: 
- Melee DPS:
- Reorganized category priorities so the stats are grouped and ordered in a consistent manner for both melee and ranged weapons.

Melee stat workers update

---

Patches/Weapons+/WeaponsPlus_MeleeWeapons.xml

- Great Axe
- Maul
- Prim Knife
- Kukri
- Glaive
- Bo
- Scythe
- Naginata
- Brass Knuckles
- Tonfa
- Katana
- Claymore
- Zweihander
- Sabre
- Flail
- **Removed:**  Handle / Chain / Spikes
- Nunchaku
- **Removed:**  Handle / Chain
- Morning Star
- **Removed:** Blade
- Bardiche
- **Removed:** Blade
- Kunai

Weapons+ Update

---

Patches/Core/ThingDefs_Buildings/Buildings_Base.xml

Recurve bows use this arrow type.

Add damage reduction to high-velocity arrows

---

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeDamage.cs
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeDamageAverage.cs
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MeleeDamageBase.cs

Fix damage display in info windows

---

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs

New armor system displays for gear tab

---

Defs/Ammo/Neolithic/Arrows.xml

Recurve bow arrow re-use fix

---

Patches/CuprosAlloys/ThingDefs/Patch_Materials_Alloy_Advanced.xml
Patches/CuprosAlloys/ThingDefs/Patch_Materials_Alloy_Decorative.xml
Patches/CuprosAlloys/ThingDefs/Patch_Materials_Alloy_Utility.xml
Patches/CuprosAlloys/ThingDefs/Patch_Materials_BaseMetal.xml
Patches/RoM - Bones/ThingDefs_Items/Patch_Items_Apparel_BoneMasks.xml
Patches/Spartan Foundry/ThingDefs_Misc/Patch_Apparel_Headgear.xml
Patches/Vanilla Apparel Expanded/Patch_Apparel_Footwear.xml
Patches/Vanilla Apparel Expanded/Patch_Apparel_Handwear.xml
Patches/Vanilla Apparel Expanded/Patch_Apparel_Industrial.xml
Patches/Vanilla Apparel Expanded/Patch_Apparel_Medieval.xml
Patches/Vanilla Apparel Expanded/Patch_Apparel_Neolithic.xml
Patches/Vanilla Apparel Expanded/Patch_Headgear_Industrial.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Footwear.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Handwear.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Industrial.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Medieval.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Neolithic.xml
Patches/Vanilla Armour Expanded/Patch_Armor_Spacer.xml
Patches/Vanilla Armour Expanded/Patch_Headgear_Industrial.xml

Updated or fixed these mods:
- Vanilla Apparel Expanded;
- Vanilla Armour Expanded;
- Spartan Foundry;
- Rim of Madness - Bones;
- Cupro's Alloys.

Updated my patches to be up-to-date with CE changes and the mods themselves.

---

Patches/ADogSaid/Bionics.xml
Patches/EPOE/Bionics.xml
Patches/Hand- and Footwear/ThingDefs_Misc/HnF_Apparel_Footwear.xml
Patches/Hand- and Footwear/ThingDefs_Misc/HnF_Apparel_Handwear.xml
Patches/O21 Races/Elven Faction/PawnKindDefs/Elves_PawnKinds.xml
Patches/O21 Races/Elves/Scenarios/Scenarios.xml
Patches/O21 Races/Elves/ThingDefs_Races/Race_ElfBase.xml
Patches/O21 Races/Goblin Faction/PawnKindDefs/Goblins_PawnKinds.xml
Patches/O21 Races/Goblins/Scenarios/Scenarios.xml
Patches/O21 Races/Goblins/ThingDefs_Races/Race_Goblin.xml
Patches/O21 Races/Kobolds/Scenarios/Scenarios.xml
Patches/O21 Races/Kobolds/ThingDefs_Races/Race_Kobold.xml
Patches/RBSE/Bionics.xml

Added patch for O21 Race mods (kobolds, elves, goblins + factions), including weaponMoney fix for base mod issue.
Updated patches for:
- A Dog Said...
- EPOE
- RBSE
- Hand & Footwear

Updated some patches to 1.6

---

Defs/ThingCategoryDefs/ThingCategories.xml
Defs/ThingDefs_Misc/Apparel_Shield.xml

A simple QoL adjustment I've had for CE: Shields for a while. Adds a separate sub-category for shields to organize things a little better for creating loadouts.

Add separate ThingCategory for Shields for better loadout creation.

---

Patches/Dinosauria/Races_Animal_Dinosauria.xml

Dinosauria patch

---

Patches/Dinosauria/Races_Animal_Dinosauria.xml

Now properly done with references to CE sheets

Balance update

---

Patches/Xenohumans/Races_Designermate_XH.xml
Patches/Xenohumans/Races_Scaleman_XH.xml
Patches/Xenohumans/Races_Soldiermorph_XH.xml
Patches/Xenohumans/Races_Wolfman_XH.xml

- */ to Defs/ 
- PatchOperationFindMod target changed

Xenohumans patch changes

---

Patches/Core/Bodies/Bodies_Humanlike/Human.xml

Adds CoveredByNaturalArmor to human outer body parts, allowing alien races using the human bodyDef to have sharp/blunt armor applied.

Add natural armor for humans

---

Defs/DamageDefs/Damages_LocalInjury.xml
Patches/Core/DamageDefs/Damages_BuildingModifiers.xml

Remove melee building modifiers

---

Defs/Ammo/Shell/81mmMortar.xml
Patches/Core/Scenarios/Scenarios.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml
Patches/Core/ThingDefs_Items/Items_General.xml
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs

- Set javelin count in Lost Tribe start, as this weapon is a consumable in CE
- Social fights no longer parry/riposte with their weapons
- Tweaked mortar chargeSpeeds to reduce travel time in lower gravity
- Added mass/bulk for tusks/horns, and fixed their descriptions to not mention them as a usable weapon

Misc fixes

---

Defs/Ammo/Rifle/7.92x57mmMauser.xml
Languages/Korean/defInjected/CombatExtended.AmmoSetDefs/7.92x57mmMauser.xml
Languages/Korean/defInjected/RecipeDefs/7.92x57mmMauser.xml
Languages/Korean/defInjected/ThingCategoryDefs/7.92x57mmMauser.xml
Languages/Korean/defInjected/ThingDefs/7.92x57mmMauser.xml
Languages/Russian/DefInjected/CombatExtended.AmmoSetDef/7.92x57mmMauser.xml
Languages/Russian/DefInjected/RecipeDef/7.92x57mmMauser.xml
Languages/Russian/DefInjected/ThingCategoryDef/7.92x57mmMauser.xml
Languages/Russian/DefInjected/ThingDef/7.92x57mmMauser.xml
Languages/Spanish/DefInjected/CombatExtended.AmmoSetDef/7.92x57mmMauser.xml
Languages/Spanish/DefInjected/RecipeDef/7.92x57mmMauser.xml
Languages/Spanish/DefInjected/ThingCategoryDef/7.92x57mmMauser.xml
Languages/Spanish/DefInjected/ThingDef/7.92x57mmMauser.xml
Languages/SpanishLatin/DefInjected/CombatExtended.AmmoSetDef/7.92x57mmMauser.xml
Languages/SpanishLatin/DefInjected/RecipeDef/7.92x57mmMauser.xml
Languages/SpanishLatin/DefInjected/ThingCategoryDef/7.92x57mmMauser.xml
Languages/SpanishLatin/DefInjected/ThingDef/7.92x57mmMauser.xml

Reverts NoImageAvailable/CombatExtended#933

Revert "Fix incorrect defName for 7.92x57mm Mauser rifle cartridge"

---

Source/CombatExtended/CombatExtended/Jobs/JobDriver_Hunt.cs

When hunting with a melee weapon, the CastVerb approach only uses the primary verb for attacks. Using a melee attack toil when using melee weapons to hunt fixes this.

Fix melee hunting not using all available tools

---

Source/CombatExtended/CombatExtended.csproj
Source/CombatExtended/Harmony/Harmony_AttackTargetFinder.cs

Lets stuff like EMP shotguns automatically engage organics, as in CE this damage type isn't useless against them.

Allow EMP auto-attack on organic targets

---

Patches/Orassans/ThingDefs_Races/Orassan_Race.xml

Add validation in Orassans patch

---

Patches/Black Widows/ThingDefs_Items/Patch_Items_Resources.xml

This has been on my mind for a long time. Better late than never.

Updated the Black Widow patch to reduce fabric heat protection to 0.

---

Patches/Simply More Melee/SMM_MeleeWeapons_CE.xml

* New weapons
* Added weapon tags for one-handed and sidearms

Simply More Melee patch update

---

Patches/MiscRobots/AIRobot_RacesCE.xml

Silly roomba, you don't even have lungs!

Add smoke immunity to Misc Robots

---

Patches/Core/ThingDefs_Races/Races_Animal_Bears.xml
Patches/Core/ThingDefs_Races/Races_Animal_BigCat.xml
Patches/Core/ThingDefs_Races/Races_Animal_Hares.xml
Patches/Core/ThingDefs_Races/Races_Animal_Pet.xml
Patches/Core/ThingDefs_Races/Races_Animal_Tropical.xml
Patches/Core/ThingDefs_Races/Races_Animal_WildCanines.xml

- Made all changes listed on Melee Changes - 2/23 sheet.
- Reduced cat Bite contact area in line with other predator contact area changes.
- Fixed cobra ToxicBite using incorrect BladeLength,

Buffed predator Sharp AP

---

Languages/ChineseSimplified/DefInjected/StatDef/Stats_Weapons_Ranged.xml

Reverts CombatExtendedRWMod/CombatExtended#1000

Revert "Chinese translation update"

---

Languages/ChineseSimplified/DefInjected/StatDef/Stats_Pawns_Combat.xml

Reverts CombatExtendedRWMod/CombatExtended#1001

Revert "Chinese translation update 2"

---

Languages/ChineseSimplified/DefInjected/StatDef/Stats_Basics_Inventory.xml

Reverts CombatExtendedRWMod/CombatExtended#1002

Revert "Chinese translation update 3"

---

Languages/ChineseSimplified/DefInjected/StatDef/Stats_Apparel.xml

Reverts CombatExtendedRWMod/CombatExtended#1003

Revert "Chinese translation update 4"

---

Languages/ChineseSimplified/DefInjected/StatDef/Stats_Pawns_General.xml

Reverts CombatExtendedRWMod/CombatExtended#1004

Revert "Chinese translation update 5"

---

Languages/ChineseSimplified/DefInjected/StatDef/Stats_Weapons_Melee.xml

Reverts CombatExtendedRWMod/CombatExtended#1005

Revert "Chinese translation update 6"

---

Defs/Ammo/HighCaliber/12.7x108mmSoviet.xml
Defs/Ammo/HighCaliber/20x102mmNATO.xml
Defs/Ammo/HighCaliber/20x128mmOerlikon.xml
Defs/Ammo/HighCaliber/25x137mmNATO.xml
Defs/Ammo/HighCaliber/30x173mmNATO.xml
Defs/Ammo/Medieval/CrossbowBolts.xml
Defs/Ammo/Neolithic/Arrows.xml
Defs/Ammo/Neolithic/GreatArrows.xml
Defs/Ammo/Pistols/455Webley.xml
Defs/Ammo/Pistols/765x20mmLongue.xml
Defs/Ammo/Rocket/130mmType63.xml
Defs/Ammo/Rocket/70mmAPKWS.xml
Defs/Ammo/Rocket/TomahawkLAM.xml

- Tweaked FT core ammunition to match CE sheet calculations.
- Added venom and flaming arrows to crossbow bolts.
- Some minor housekeeping.

Tweak FT ammo, add additional ammo.

---

Patches/WWII Soviet Faction/WWIISovietFaction_CE_Patch_Clothing.xml
Patches/WWII Soviet Faction/WWIISovietFaction_CE_Patch_Headgear.xml
Patches/WWII Soviet Faction/WWIISovietFaction_CE_Patch_PawnKindDefs.xml
Patches/WWII Soviet Faction/WWIISovietFaction_CE_Patch_RangedIndustrial.xml
Patches/WWII Soviet Faction/WWIISovietFaction_CE_Patch_Turret.xml

Add WWII Soviet Faction patches

---

Patches/Nihal/ThingDefs_Weapons/Weapons.xml

* Update NiHal weapon melee tools
* Fix inconsistent indentation

Update NiHal patches

---

Patches/FashionRIMsta/ThingsDefs_Misc/FashionRIMsta_Apparel.xml

* Add `SmokeSensitivity` equippedStatOffset, `WearingGasMask` hediff and `StrappedHead` apparel layer to gas mask
* Fix indentation

Update FashionRIMsta patches

---

Patches/High Caliber/HighCaliber_CE_Patch_Weapons.xml

Notes:
* The original mod is literally named "High Caliber", but is not actually restricted to such weapons

Add High Caliber mod patches

---

Patches/Android Tiers/Ammo/81mmMortar_Nanoshell.xml
Patches/Android Tiers/Bodies/Mod_Bodies_AT_ABird.xml
Patches/Android Tiers/Bodies/Mod_Bodies_AT_K9.xml
Patches/Android Tiers/Bodies/Mod_Bodies_AT_M7Mech.xml
Patches/Android Tiers/Bodies/Mod_Bodies_AT_Miniscyther.xml
Patches/Android Tiers/Bodies/Mod_Bodies_AT_Muff.xml
Patches/Android Tiers/Bodies/Mod_Bodies_AT_T4Android.xml
Patches/Android Tiers/Hediffs/Hediffs_Android.xml
Patches/Android Tiers/PawnkindDefs/PawnKinds_Android.xml
Patches/Android Tiers/ThingDef_Races/AlienRace_Androids.xml
Patches/Android Tiers/ThingDef_Races/Races.xml

Reverts CombatExtendedRWMod/CombatExtended#1076

Revert "Update to non-weapon Android Tier patches"

---

Patches/Let's Have a Cat!/LHaC_CE_Patch_Races_Animal_NEKO.xml

Patch brought over as part of the FastTrack merger
Same stats and melee tools as cats from the vanilla game (Core)

Add Let's Have a Cat! patch

---

Patches/MechanoidsExtraordinaire/BodyDefs/BodyParts_Mechanoid_Internal.xml
Patches/MechanoidsExtraordinaire/HediffDefs/Hediffs_Local_AddedParts_MechanoidsExtraordinaire.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Races/Races_Mechanoid_MechanoidsExtraordinaire.xml
Source/CombatExtended/Harmony/HarmonyThingDef.cs

* Update Mechanoid melee tools 
* Update hediff defNames

Update Mechanoids Extraordinaire patches

---

Defs/ThingDefs_Misc/Weapons_Ranged.xml

Removed researchPrerequisite and crafting stats. Updated description.

Explosive Bolt Projector tweaks.

---

Patches/Core/DamageDefs/Damages_LocalInjury.xml
Royalty/Patches/HeDiffDefs/Hediffs_Implants.xml
Royalty/Patches/ThingDefs_Buildings/Buildings_Mechanoid.xml
Royalty/Patches/ThingDefs_Misc/Apparel_Headgear.xml
Royalty/Patches/ThingDefs_Misc/Apparel_Royalty.xml
Royalty/Patches/TraderKindDefs/TraderKinds_Royalty.xml

- Patches all Royalty apparel and armor.
- Patches melee tools for prosthetic
- Patches Toughskin/Armorskin/Stoneskin implants to CE armor values.
- Patches ScratchVenom along the same lines as ToxicBite
- Patch Traders.

Royalty Patch - PR 1

---

About/About.xml
Patches/Soviet Armory/SovietArmory_CE_Patch_Weapons.xml
Patches/Spartan Foundry/ThingDefs_Misc/Patch_Apparel_Headgear.xml

- Fixed a couple of patches referencing workstats that no longer exist.
- Added a few hard incompatibilities to About.xml

Add some incompatibility warnings to About.xml, fixed some outdated work stats in a couple of patches.

---

Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Ranged.xml
Patches/Vanilla Weapons Expanded/Ammo/AntiGrainRocket.xml
Patches/Vanilla Weapons Expanded/Ammo/LeadBall.xml
Patches/Vanilla Weapons Expanded/Industrial_Grenades.xml
Patches/Vanilla Weapons Expanded/Medieval_Ranged.xml
Patches/Vanilla Weapons Expanded/ResearchProjects.xml

- Resolved start-up errors from VWE.
- Converted VWE to new explosive comp.
- Patched VFE - Medieval Heavy Crossbow.

Vanilla Weapons Expansion, VFE - Medieval patch tweaks.

---

Patches/O21 Races/Kobold Faction/Kobolds_PawnKinds.xml
Patches/O21 Races/Kobolds/Kobolds_Scenarios.xml
Patches/O21 Races/Kobolds/Race_Kobold.xml

Resolved a couple of errors on startup related to renamed Defs (and one typo).

O21 kobold + faction patch fixes.
